#!/usr/bin/env node

// Generates Go DTOs and TypeScript interfaces from OpenAPI spec
// - Generated by Co-Pilot
import * as yaml from "js-yaml";
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface Options {
    installTools?: boolean;
    build?: boolean;
}

const args = process.argv.slice(2);
const options: Options = {
    installTools: args.includes("--install-tools"),
    build: args.includes("--build")
};

const root = join(__dirname, "..", "..");
const specPath = join(root, "api", "openapi", "openapi.yaml");
const dtoOutPath = join(root, "internal", "dto", "types.gen.go");
const vizDir = join(root, "viewfinder");

console.log("Repo root:", root);

if (!existsSync(specPath)) {
    console.error(`OpenAPI spec not found at ${specPath}`);
    process.exit(1);
}

function run(command: string, args: string[], cwd?: string, silent = false) {
    const result = spawnSync(command, args, {
        cwd: cwd || root,
        stdio: silent ? "pipe" : "inherit",
        shell: true
    });

    // blank line for printing clarity
    console.log("");
    return result.status === 0;
}

function commandExists(cmd: string): boolean {
    const result = spawnSync(process.platform === "win32" ? "where" : "which", [cmd], {
        stdio: "pipe",
        shell: true
    });
    return result.status === 0;
}

// Optionally install tools
if (options.installTools) {
    console.log("Ensuring oapi-codegen is installed...");
    if (!commandExists("oapi-codegen")) {
        console.log("Installing oapi-codegen...");
        const installSuccess = run("go", [
            "install",
            "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest"
        ]);
        if (installSuccess) {
            // Try to locate the installed binary and add it to PATH for this process so subsequent commands can find it.
            const binName = process.platform === "win32" ? "oapi-codegen.exe" : "oapi-codegen";
            const goBin =
                process.env.GOBIN ||
                (process.env.GOPATH ? join(process.env.GOPATH, "bin") : join(process.env.HOME || "", "go", "bin"));
            const candidate = join(goBin, binName);
            if (existsSync(candidate)) {
                const pathSep = process.platform === "win32" ? ";" : ":";
                process.env.PATH = `${goBin}${pathSep}${process.env.PATH || ""}`;
                console.log(`Added ${goBin} to PATH for this process.`);
            } else {
                console.warn(
                    `oapi-codegen installed but not found at ${candidate}. It may not be on PATH; consider adding ${goBin} to your PATH.`
                );
            }
        } else {
            console.warn(
                "`go install` for oapi-codegen failed. The generator may still run via `go run`, but the binary was not installed."
            );
        }
    }

    console.log("Ensuring pnpm dev dep openapi-typescript is installed...");
    if (existsSync(vizDir) && commandExists("pnpm")) {
        console.log("Adding openapi-typescript to viz...");
        run("pnpm", ["add", "-D", "openapi-typescript@^7.5.0"], vizDir, true);
    } else if (!commandExists("pnpm")) {
        console.warn("pnpm not found. Skipping TS generator install; assuming it's available in PATH.");
    }
}

// Ensure oapi runtime dependency exists
console.log("Ensuring Go runtime dependency for oapi-codegen is present...");
const hasRuntime = run("go", ["list", "-m", "github.com/oapi-codegen/runtime"], root, true);
if (!hasRuntime) {
    console.log("Adding oapi-codegen runtime dependency...");
    run("go", ["get", "github.com/oapi-codegen/runtime/types@v1.1.0"]);
}

// Generate Go DTOs
console.log(`Generating Go DTOs from ${specPath} -> ${dtoOutPath}`);
const goGenSuccess = run("go", [
    "run",
    "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest",
    "-generate",
    "types,skip-prune",
    "-package",
    "dto",
    "-o",
    dtoOutPath,
    specPath
]);

if (!goGenSuccess) {
    console.error("Failed to generate Go DTOs");
    process.exit(1);
}

// Generate Go types+client into pkg/openapi so package is self-contained for public use.
const outDir = join(root, "pkg", "openapi");
const typesOut = join(outDir, "types.gen.go");
const clientOut = join(outDir, "client.gen.go");
console.log(`Generating Go types + client into ${outDir}`);

// ensure outDir exists
try {
    mkdirSync(outDir, { recursive: true });
} catch (e) {
    /* ignore */
}

// Generate types into pkg/openapi (keeps a local copy for the public package)
const typesSuccess = run("go", [
    "run",
    "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest",
    "-generate",
    "types,skip-prune",
    "-package",
    "openapi",
    "-o",
    typesOut,
    specPath
]);
if (!typesSuccess) {
    console.warn("oapi-codegen types generation into pkg/openapi failed; pkg/openapi will not contain types");
} else {
    console.log("oapi-codegen types generated to", typesOut);
}

// Generate client into pkg/openapi
const clientSuccess = run("go", [
    "run",
    "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest",
    "-generate",
    "client",
    "-package",
    "openapi",
    "-o",
    clientOut,
    specPath
]);

if (!clientSuccess) {
    console.error("oapi-codegen client generation failed; skipping Go client generation");
} else {
    console.log("oapi-codegen client generated to", clientOut);
}

if (!typesSuccess && !existsSync(dtoOutPath)) {
    console.warn("No types available in pkg/openapi OR internal/dto; ensure oapi-codegen types run succeeded earlier.");
}

// Tidy modules (optional, only if new dependencies were added)
if (options.installTools || !hasRuntime) {
    console.log("Running go mod tidy...");
    run("go", ["mod", "tidy"]);
} else {
    console.log("Skipping go mod tidy (use --install-tools to force)");
}

// Generate GORM entities from DTOs
const genEntitiesBinary = process.platform === "win32" ? "genentities.exe" : "genentities";
const genEntitiesPath = join(root, "tools", "genentities", genEntitiesBinary);

let genEntitiesSuccess = false;

if (existsSync(genEntitiesPath)) {
    console.log(`Generating GORM entities using binary (${genEntitiesPath})...`);
    // On Windows/Shell, passing the absolute path usually works fine.
    genEntitiesSuccess = run(genEntitiesPath, ["-openapi", specPath]);
} else {
    console.log("Generating GORM entities from DTOs (go run ./tools/genentities)...");
    genEntitiesSuccess = run("go", ["run", "./tools/genentities", "-openapi", specPath]);
}

if (!genEntitiesSuccess) {
    console.error("Failed to generate GORM entities");
    process.exit(1);
}

// Generate TS API client with oazapfts
if (existsSync(vizDir)) {
    console.log("Generating TypeScript API client with oazapfts...");
    const pkgJsonPath = join(vizDir, "package.json");

    if (existsSync(pkgJsonPath)) {
        if (commandExists("pnpm")) {
            const tsGenSuccess = run("pnpm", ["run", "gen:api"], vizDir);
            if (!tsGenSuccess) {
                console.warn("pnpm run gen:api failed; trying npx fallback...");
                run("npx", ["oazapfts", specPath, join("src", "lib", "api", "client.gen.ts")], vizDir);
            }
        } else {
            console.warn("pnpm not found; trying npx oazapfts...");
            run("npx", ["oazapfts", specPath, join("src", "lib", "api", "client.gen.ts")], vizDir);
        }
    }

    // Generate scopes from BearerAuth security scheme
    try {
        console.log("Generating scopes.gen.ts from OpenAPI x-scopes...");
        const specContent = readFileSync(specPath, "utf-8");
        const doc = yaml.load(specContent) as any;
        const scopesMap = doc?.components?.securitySchemes?.BearerAuth?.["x-scopes"];

        if (scopesMap) {
            const scopeKeys: string[] = [];
            const scopeItems: { value: string; label: string }[] = [];

            const scopeToKey = (scope: string): string => {
                if (scope === "*") {
                    return "FullAccess";
                }
                const parts = scope.split(/[:\-]/);
                return parts
                    .map((part) => {
                        if (part === "api") {
                            return "API";
                        }
                        return part.charAt(0).toUpperCase() + part.slice(1);
                    })
                    .join("");
            };

            for (const [value, label] of Object.entries(scopesMap)) {
                const key = scopeToKey(value);
                scopeKeys.push(`    ${key} = "${value}"`);
                scopeItems.push({ value, label: label as string });
            }

            const scopesGenContent = `/**
 * DO NOT MODIFY - This file has been generated from OpenAPI spec.
 * See scripts/js/gen-api.ts
 */

export enum Scope {
${scopeKeys.join(",\n")}
}

export interface ScopeItem {
    value: Scope;
    label: string;
}

export const scopes: ScopeItem[] = [
${scopeItems.map((item) => `    { value: Scope.${scopeToKey(item.value)}, label: "${item.label}" }`).join(",\n")}
];
`;
            const scopesGenPath = join(vizDir, "src", "lib", "auth", "scopes.gen.ts");
            writeFileSync(scopesGenPath, scopesGenContent, "utf-8");
            console.log(`Successfully generated scopes to ${scopesGenPath}`);

            // Generate Go scopes
            const scopeKeysGo: string[] = [];
            const scopeItemsGo: string[] = [];

            const scopeToGoKey = (scope: string): string => {
                if (scope === "*") {
                    return "AllScope";
                }
                const cleaned = scope.replace("api-keys", "APIKeys");
                const parts = cleaned.split(/[:\-]/);
                const pascal = parts
                    .map((part) => {
                        if (part === "APIKeys") {
                            return "APIKeys";
                        }
                        return part.charAt(0).toUpperCase() + part.slice(1);
                    })
                    .join("");
                return pascal + "Scope";
            };

            for (const [value, label] of Object.entries(scopesMap)) {
                const goKey = scopeToGoKey(value);
                scopeKeysGo.push(`\t// ${goKey} grants permission for ${value}.\n\t${goKey} Scope = "${value}"`);
                scopeItemsGo.push(`\t{Value: ${goKey}, Label: "${label}"}`);
            }

            const goGenContent = `// Code generated by scripts/js/gen-api.ts. DO NOT EDIT.
package auth

const (
${scopeKeysGo.join("\n")}
)

// AllScopes is a list of all available scopes.
var AllScopes = []ScopeItem{
${scopeItemsGo.join(",\n")},
}
`;
            const goGenPath = join(root, "internal", "auth", "scopes.gen.go");
            writeFileSync(goGenPath, goGenContent, "utf-8");
            console.log(`Successfully generated Go scopes to ${goGenPath}`);
        } else {
            console.warn("No x-scopes found in BearerAuth security scheme.");
        }
    } catch (err) {
        console.error("Failed to generate scopes.gen.ts:", err);
    }
}

// Optional build checks
if (options.build) {
    console.log("Running Go build...");
    const goBuildSuccess = run("go", ["build", "./..."]);
    if (!goBuildSuccess) {
        console.warn("Go build failed.");
    }

    if (existsSync(vizDir) && commandExists("pnpm")) {
        console.log("Running Svelte/TS check...");
        const checkSuccess = run("pnpm", ["run", "check"], vizDir);
        if (!checkSuccess) {
            console.warn("viz check failed (this may be unrelated to API types).");
        }
    }
}

console.log("Done.");
