#!/usr/bin/env node

// Generates Go DTOs and TypeScript interfaces from OpenAPI spec
// - Generated by Co-Pilot
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface Options {
    installTools?: boolean;
    build?: boolean;
}

const args = process.argv.slice(2);
const options: Options = {
    installTools: args.includes('--install-tools'),
    build: args.includes('--build'),
};

const root = join(__dirname, '..', '..');
const specPath = join(root, 'api', 'openapi', 'openapi.yaml');
const dtoOutPath = join(root, 'internal', 'dto', 'types.gen.go');
const vizDir = join(root, 'viz');

console.log('Repo root:', root);

if (!existsSync(specPath)) {
    console.error(`OpenAPI spec not found at ${specPath}`);
    process.exit(1);
}

function run(command: string, args: string[], cwd?: string, silent = false) {
    const result = spawnSync(command, args, {
        cwd: cwd || root,
        stdio: silent ? 'pipe' : 'inherit',
        shell: true,
    });
    return result.status === 0;
}

function commandExists(cmd: string): boolean {
    const result = spawnSync(process.platform === 'win32' ? 'where' : 'which', [cmd], {
        stdio: 'pipe',
        shell: true,
    });
    return result.status === 0;
}

// Optionally install tools
if (options.installTools) {
    console.log('Ensuring oapi-codegen is installed...');
    if (!commandExists('oapi-codegen')) {
        console.log('Installing oapi-codegen...');
        run('go', ['install', 'github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest']);
    }

    console.log('Ensuring pnpm dev dep openapi-typescript is installed...');
    if (existsSync(vizDir) && commandExists('pnpm')) {
        console.log('Adding openapi-typescript to viz...');
        run('pnpm', ['add', '-D', 'openapi-typescript@^7.5.0'], vizDir, true);
    } else if (!commandExists('pnpm')) {
        console.warn('pnpm not found. Skipping TS generator install; assuming it\'s available in PATH.');
    }
}

// Ensure oapi runtime dependency exists
console.log('Ensuring Go runtime dependency for oapi-codegen is present...');
const hasRuntime = run('go', ['list', '-m', 'github.com/oapi-codegen/runtime'], root, true);
if (!hasRuntime) {
    console.log('Adding oapi-codegen runtime dependency...');
    run('go', ['get', 'github.com/oapi-codegen/runtime/types@v1.1.0']);
}

// Generate Go DTOs
console.log(`Generating Go DTOs from ${specPath} -> ${dtoOutPath}`);
const goGenSuccess = run('oapi-codegen', [
    '-generate',
    'types',
    '-package',
    'dto',
    '-o',
    dtoOutPath,
    specPath,
]);

if (!goGenSuccess) {
    console.error('Failed to generate Go DTOs');
    process.exit(1);
}

// Tidy modules (optional, only if new dependencies were added)
if (options.installTools || !hasRuntime) {
    console.log('Running go mod tidy...');
    run('go', ['mod', 'tidy']);
} else {
    console.log('Skipping go mod tidy (use --install-tools to force)');
}

// Generate GORM entities that embed DTOs
console.log('Generating GORM entities from DTOs (go run ./tools/genentities)...');
const genEntitiesSuccess = run('go', ['run', './tools/genentities']);
if (!genEntitiesSuccess) {
    console.error('Failed to generate GORM entities');
    process.exit(1);
}

// Generate TS API client with oazapfts
if (existsSync(vizDir)) {
    console.log('Generating TypeScript API client with oazapfts...');
    const pkgJsonPath = join(vizDir, 'package.json');

    if (existsSync(pkgJsonPath)) {
        if (commandExists('pnpm')) {
            const tsGenSuccess = run('pnpm', ['run', 'gen:api'], vizDir);
            if (!tsGenSuccess) {
                console.warn('pnpm run gen:api failed; trying npx fallback...');
                run('npx', [
                    'oazapfts',
                    join('..', 'api', 'openapi', 'openapi.yaml'),
                    join('src', 'lib', 'api', 'client.gen.ts'),
                ], vizDir);
            }
        } else {
            console.warn('pnpm not found; trying npx oazapfts...');
            run('npx', [
                'oazapfts',
                join('..', 'api', 'openapi', 'openapi.yaml'),
                join('src', 'lib', 'api', 'client.gen.ts'),
            ], vizDir);
        }
    }
}

// Generate Go types+client into pkg/openapi so package is self-contained for public use.
{
    const outDir = join(root, 'pkg', 'openapi');
    const typesOut = join(outDir, 'types.gen.go');
    const clientOut = join(outDir, 'client.gen.go');
    console.log(`Generating Go types + client into ${outDir}`);

    // ensure outDir exists
    try { mkdirSync(outDir, { recursive: true }); } catch (e) { /* ignore */ }

    // Generate types into pkg/openapi (keeps a local copy for the public package)
    const typesSuccess = run('oapi-codegen', [
        '-generate', 'types',
        '-package', 'openapi',
        '-o', typesOut,
        specPath,
    ]);
    if (!typesSuccess) {
        console.warn('oapi-codegen types generation into pkg/openapi failed; pkg/openapi will not contain types');
    } else {
        console.log('oapi-codegen types generated to', typesOut);
    }

    // Generate client into pkg/openapi
    const clientSuccess = run('oapi-codegen', [
        '-generate', 'client',
        '-package', 'openapi',
        '-o', clientOut,
        specPath,
    ]);

    if (!clientSuccess) {
        console.error('oapi-codegen client generation failed; skipping Go client generation');
    } else {
        console.log('oapi-codegen client generated to', clientOut);
    }

    if (!typesSuccess && !existsSync(dtoOutPath)) {
        console.warn('No types available in pkg/openapi OR internal/dto; ensure oapi-codegen types run succeeded earlier.');
    }
}

// Remove old function generation (no longer needed with oazapfts)
// oazapfts generates both types AND functions in one file

// Optional build checks
if (options.build) {
    console.log('Running Go build...');
    const goBuildSuccess = run('go', ['build', './...']);
    if (!goBuildSuccess) {
        console.warn('Go build failed.');
    }

    if (existsSync(vizDir) && commandExists('pnpm')) {
        console.log('Running Svelte/TS check...');
        const checkSuccess = run('pnpm', ['run', 'check'], vizDir);
        if (!checkSuccess) {
            console.warn('viz check failed (this may be unrelated to API types).');
        }
    }
}

console.log('Done.');
