packages:
  - 'packages/*'
  - 'viewfinder'
  - 'scripts/js'
allowBuilds:
  '@parcel/watcher': false
  esbuild: false
peerDependencyRules:
  allowedVersions:
    prettier-plugin-svelte: 4.x
    typescript: 6.x
