/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health ping */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an image (multipart) */
        post: operations["uploadImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an image by URL */
        post: operations["uploadImageByUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/{uid}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a processed image file */
        get: operations["getImageFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List collections */
        get: operations["listCollections"];
        put?: never;
        /** Create a collection */
        post: operations["createCollection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get collection detail */
        get: operations["getCollection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{uid}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List images in a collection */
        get: operations["listCollectionImages"];
        /** Add images to a collection */
        put: operations["addCollectionImages"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Pagination: {
            href: string;
            prev?: string;
            next?: string;
            limit: number;
            offset: number;
            count: number;
        };
        ImageEXIF: {
            exif_version?: string;
            make?: string;
            model?: string;
            date_time?: string;
            date_time_original?: string;
            iso?: string;
            focal_length?: string;
            exposure_time?: string;
            aperture?: string;
            flash?: string;
            white_balance?: string;
            lens_model?: string;
            modify_date?: string;
            rating?: string;
            orientation?: string;
            resolution?: string;
            software?: string;
            longitude?: string;
            latitude?: string;
        };
        ImagePaths: {
            original_path: string;
            thumbnail_path: string;
            preview_path: string;
            raw_path?: string;
        };
        ImageMetadata: {
            file_name: string;
            /** Format: int64 */
            file_size?: number;
            original_file_name?: string;
            file_type: string;
            keywords?: string[];
            color_space: string;
            /** Format: date-time */
            file_modified_at: string;
            /** Format: date-time */
            file_created_at: string;
            thumbhash?: string;
            label?: string;
            checksum: string;
        };
        Image: {
            uid: string;
            name: string;
            uploaded_by?: string;
            description?: string;
            exif?: components["schemas"]["ImageEXIF"];
            private: boolean;
            /** Format: int32 */
            width: number;
            /** Format: int32 */
            height: number;
            processed: boolean;
            image_metadata?: components["schemas"]["ImageMetadata"];
            image_paths?: components["schemas"]["ImagePaths"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CollectionImage: {
            uid: string;
            /** Format: date-time */
            added_at: string;
            added_by?: string;
        };
        Collection: {
            uid: string;
            name: string;
            image_count: number;
            private?: boolean | null;
            images?: components["schemas"]["CollectionImage"][];
            created_by?: string;
            description?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CollectionCreate: {
            name: string;
            private?: boolean | null;
            description?: string;
        };
        ImagesResponse: {
            /** Format: date-time */
            added_at: string;
            added_by?: string;
            image: components["schemas"]["Image"];
        };
        ImagesPage: {
            href?: string;
            prev?: string;
            next?: string;
            limit: number;
            offset: number;
            count?: number;
            items: components["schemas"]["ImagesResponse"][];
        };
        CollectionListResponse: {
            href?: string;
            prev?: string;
            next?: string;
            limit: number;
            offset: number;
            count?: number;
            items: components["schemas"]["Collection"][];
        };
        CollectionDetailResponse: {
            uid: string;
            name: string;
            image_count?: number;
            private?: boolean | null;
            images: components["schemas"]["ImagesPage"];
            created_by?: string;
            description?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    uploadImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    filename: string;
                    /** Format: binary */
                    data: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                    };
                };
            };
        };
    };
    uploadImageByUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/plain": string;
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                    };
                };
            };
        };
    };
    getImageFile: {
        parameters: {
            query?: {
                format?: "webp" | "png" | "jpg" | "jpeg" | "avif" | "heif";
                w?: number;
                h?: number;
                quality?: number;
            };
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
        };
    };
    listCollections: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collections page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionListResponse"];
                };
            };
        };
    };
    createCollection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
        };
    };
    getCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collection detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDetailResponse"];
                };
            };
        };
    };
    listCollectionImages: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Images page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImagesPage"];
                };
            };
        };
    };
    addCollectionImages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    uids: string[];
                };
            };
        };
        responses: {
            /** @description Images added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        added: boolean;
                    };
                };
            };
        };
    };
}
