export enum Scope {
    FullAccess = "*",
    AdminRead = "admin:read",
    AdminWrite = "admin:write",
    APIKeysCreate = "api-keys:create",
    APIKeysList = "api-keys:list",
    APIKeysRead = "api-keys:read",
    APIKeysRevoke = "api-keys:revoke",
    APIKeysRotate = "api-keys:rotate",
    APIKeysDelete = "api-keys:delete",
    AuthRefresh = "auth:refresh",
    AuthRevoke = "auth:revoke",
    CollectionsCreate = "collections:create",
    CollectionsRead = "collections:read",
    CollectionsUpdate = "collections:update",
    CollectionsDelete = "collections:delete",
    CollectionsShare = "collections:share",
    ImagesRead = "images:read",
    ImagesUpload = "images:upload",
    ImagesUpdate = "images:update",
    ImagesDelete = "images:delete",
    ImagesDownload = "images:download",
    JobsRead = "jobs:read",
    JobsCreate = "jobs:create",
    JobsUpdate = "jobs:update",
    JobsDelete = "jobs:delete",
    UsersCreate = "users:create",
    UsersRead = "users:read",
    UsersUpdate = "users:update",
    UsersDelete = "users:delete",
    UserSettingsRead = "user-settings:read",
    UserSettingsUpdate = "user-settings:update",
    DownloadsCreate = "downloads:create",
    EventsRead = "events:read"
}

export interface ScopeItem {
    value: Scope;
    label: string;
}

export const scopes: ScopeItem[] = [
    { value: Scope.FullAccess, label: "Full Access" },
    { value: Scope.AdminRead, label: "Admin Read" },
    { value: Scope.AdminWrite, label: "Admin Write" },
    { value: Scope.APIKeysCreate, label: "Create API Keys" },
    { value: Scope.APIKeysList, label: "List API Keys" },
    { value: Scope.APIKeysRead, label: "Read API Key" },
    { value: Scope.APIKeysRevoke, label: "Revoke API Keys" },
    { value: Scope.APIKeysRotate, label: "Rotate API Keys" },
    { value: Scope.APIKeysDelete, label: "Delete API Keys" },
    { value: Scope.AuthRefresh, label: "Refresh Auth" },
    { value: Scope.AuthRevoke, label: "Revoke Auth" },
    { value: Scope.CollectionsCreate, label: "Create Collections" },
    { value: Scope.CollectionsRead, label: "Read Collections" },
    { value: Scope.CollectionsUpdate, label: "Update Collections" },
    { value: Scope.CollectionsDelete, label: "Delete Collections" },
    { value: Scope.CollectionsShare, label: "Share Collections" },
    { value: Scope.ImagesRead, label: "Read Images" },
    { value: Scope.ImagesUpload, label: "Upload Images" },
    { value: Scope.ImagesUpdate, label: "Update Images" },
    { value: Scope.ImagesDelete, label: "Delete Images" },
    { value: Scope.ImagesDownload, label: "Download Images" },
    { value: Scope.JobsRead, label: "Read Jobs" },
    { value: Scope.JobsCreate, label: "Create Jobs" },
    { value: Scope.JobsUpdate, label: "Update Jobs" },
    { value: Scope.JobsDelete, label: "Delete Jobs" },
    { value: Scope.UsersCreate, label: "Create Users" },
    { value: Scope.UsersRead, label: "Read Users" },
    { value: Scope.UsersUpdate, label: "Update Users" },
    { value: Scope.UsersDelete, label: "Delete Users" },
    { value: Scope.UserSettingsRead, label: "Read User Settings" },
    { value: Scope.UserSettingsUpdate, label: "Update User Settings" },
    { value: Scope.DownloadsCreate, label: "Create Downloads" },
    { value: Scope.EventsRead, label: "Read Events" }
];
