package auth

***REMOVED***
	"crypto/sha256"
	"encoding/base64"
***REMOVED***
	"math/rand/v2"
	"strings"
***REMOVED***

func HashSecret(secret string***REMOVED*** (string, error***REMOVED*** {
	shaHash := sha256.New(***REMOVED***
	_, err := shaHash.Write([]byte(secret***REMOVED******REMOVED***

***REMOVED***
		return "", err
***REMOVED***

	hashedSecret := shaHash.Sum(nil***REMOVED***
	return base64.StdEncoding.EncodeToString(hashedSecret***REMOVED***, nil
***REMOVED***

func GenerateAPIKey(***REMOVED*** (map[string]string, error***REMOVED*** {
	keyBytes, err := GenerateRandomBytes(32***REMOVED***

***REMOVED***
		fmt.Println("Error generating random bytes:", err***REMOVED***
		return map[string]string{
			"consumer_key": "",
			"hashed_key":   "",
***REMOVED*** err
***REMOVED***

	randomHorseName := strings.ToLower(HorseNames[rand.IntN(len(HorseNames***REMOVED******REMOVED***]***REMOVED***
	randomHorseBytes := []byte(randomHorseName***REMOVED***

	// Max length for the horse name bytes should be 24, so any names shorter than that
	// will be filled with randomly generated bytes
	randomHorseBytesGen, _ := GenerateRandomBytes(24 - len(randomHorseBytes***REMOVED******REMOVED***
	randomHorseBytesFilledToMax := append(randomHorseBytes, randomHorseBytesGen...***REMOVED***

	bytesCombined := append(keyBytes, randomHorseBytesFilledToMax...***REMOVED***

	finalConsumerKey := fmt.Sprint(APIKeyPrefix, "_", base64.StdEncoding.EncodeToString(bytesCombined***REMOVED******REMOVED***
	hashedKey, _ := HashSecret(finalConsumerKey***REMOVED***

	return map[string]string{
		"consumer_key": finalConsumerKey,
		"hashed_key":   hashedKey,
***REMOVED***, nil
***REMOVED***
