// Code generated by genentities. DO NOT EDIT.
package entities

import (
	"gorm.io/gorm"
	"imagine/internal/dto"
	"time"
)

// SettingDefault is a GORM entity inferred from dto.SettingDefault
type SettingDefault struct {
	ID        uint           `gorm:"primarykey" json:"-"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt time.Time
	UpdatedAt time.Time
	// AllowedValues List of valid choices if type is enum.
	AllowedValues *[]string `gorm:"serializer:json;type:JSONB"`
	// Description Description for UI
	Description string
	// DisplayName A readable and UI-friendly name for the setting (not required but highly recommended).
	DisplayName string
	// Group Category/group for the setting (e.g., General, Notifications).
	Group string
	// IsUserEditable Describes whether a user can edit this setting.
	IsUserEditable bool
	// Name Unique name for the setting (primary key).
	Name string `gorm:"uniqueIndex:idx_setting_defaults_name,priority:1"`
	// Value The default value everyone gets.
	Value string
	// ValueType Data type of the setting.
	ValueType dto.SettingDefaultValueType `gorm:"type:text"`
}

func (e SettingDefault) DTO() dto.SettingDefault {
	return dto.SettingDefault{
		AllowedValues:  e.AllowedValues,
		Description:    e.Description,
		DisplayName:    e.DisplayName,
		Group:          e.Group,
		IsUserEditable: e.IsUserEditable,
		Name:           e.Name,
		Value:          e.Value,
		ValueType:      e.ValueType,
	}
}

func SettingDefaultFromDTO(d dto.SettingDefault) SettingDefault {
	return SettingDefault{
		AllowedValues:  d.AllowedValues,
		Description:    d.Description,
		DisplayName:    d.DisplayName,
		Group:          d.Group,
		IsUserEditable: d.IsUserEditable,
		Name:           d.Name,
		Value:          d.Value,
		ValueType:      d.ValueType,
	}
}

// DownloadToken is a GORM entity inferred from dto.DownloadToken
type DownloadToken struct {
	ID        uint           `gorm:"primarykey" json:"-"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt time.Time
	UpdatedAt time.Time
	// AllowDownload Whether downloads are permitted with this token
	AllowDownload bool
	// AllowEmbed Whether embedding on external sites is allowed (false prevents hotlinking)
	AllowEmbed bool
	// Description Optional description of this download link
	Description *string
	// ExpiresAt When this token expires (null for no expiry)
	ExpiresAt *time.Time
	// ImageUids Array of authorized image UIDs
	ImageUids []string `gorm:"serializer:json;type:JSONB"`
	// Password Optional bcrypt hash of password (null if no password protection)
	Password *string
	// ShowMetadata Whether to include EXIF and metadata in responses
	ShowMetadata bool
	// Uid 64-character hex token that serves as both unique identifier and authorization key
	Uid string `gorm:"uniqueIndex"`
}

func (e DownloadToken) DTO() dto.DownloadToken {
	return dto.DownloadToken{
		CreatedAt:     e.CreatedAt,
		UpdatedAt:     e.UpdatedAt,
		AllowDownload: e.AllowDownload,
		AllowEmbed:    e.AllowEmbed,
		Description:   e.Description,
		ExpiresAt:     e.ExpiresAt,
		ImageUids:     e.ImageUids,
		Password:      e.Password,
		ShowMetadata:  e.ShowMetadata,
		Uid:           e.Uid,
	}
}

func DownloadTokenFromDTO(d dto.DownloadToken) DownloadToken {
	return DownloadToken{
		CreatedAt:     d.CreatedAt,
		UpdatedAt:     d.UpdatedAt,
		AllowDownload: d.AllowDownload,
		AllowEmbed:    d.AllowEmbed,
		Description:   d.Description,
		ExpiresAt:     d.ExpiresAt,
		ImageUids:     d.ImageUids,
		Password:      d.Password,
		ShowMetadata:  d.ShowMetadata,
		Uid:           d.Uid,
	}
}

// Image is a GORM entity inferred from dto.Image
type Image struct {
	ID        uint           `gorm:"primarykey" json:"-"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt time.Time
	UpdatedAt time.Time
	// Description Image description
	Description *string
	Exif        *dto.ImageEXIF `gorm:"serializer:json;type:JSONB"`
	// Favourited Is favourited
	Favourited *bool
	// Height Image height
	Height        int32
	ImageMetadata *dto.ImageMetadata `gorm:"serializer:json;type:JSONB"`
	ImagePaths    dto.ImagePaths     `gorm:"serializer:json;type:JSONB"`
	// Name Image name
	Name    string
	OwnerID *string
	Owner   *User `gorm:"foreignKey:OwnerID;references:Uid"`
	// Private Is private
	Private bool
	// Processed Is processed
	Processed bool
	// TakenAt Taken time
	TakenAt *time.Time
	// Uid Image UID
	Uid          string `gorm:"uniqueIndex"`
	UploadedByID *string
	UploadedBy   *User `gorm:"foreignKey:UploadedByID;references:Uid"`
	// Width Image width
	Width int32
}

func (e Image) DTO() dto.Image {
	return dto.Image{
		CreatedAt:     e.CreatedAt,
		UpdatedAt:     e.UpdatedAt,
		Description:   e.Description,
		Exif:          e.Exif,
		Favourited:    e.Favourited,
		Height:        e.Height,
		ImageMetadata: e.ImageMetadata,
		ImagePaths:    e.ImagePaths,
		Name:          e.Name,
		Owner: func() *dto.User {
			if e.Owner != nil {
				d := e.Owner.DTO()
				return &d
			}
			return nil
		}(),
		Private:   e.Private,
		Processed: e.Processed,
		TakenAt:   e.TakenAt,
		Uid:       e.Uid,
		UploadedBy: func() *dto.User {
			if e.UploadedBy != nil {
				d := e.UploadedBy.DTO()
				return &d
			}
			return nil
		}(),
		Width: e.Width,
	}
}

func ImageFromDTO(d dto.Image) Image {
	return Image{
		CreatedAt:     d.CreatedAt,
		UpdatedAt:     d.UpdatedAt,
		Description:   d.Description,
		Exif:          d.Exif,
		Favourited:    d.Favourited,
		Height:        d.Height,
		ImageMetadata: d.ImageMetadata,
		ImagePaths:    d.ImagePaths,
		Name:          d.Name,
		OwnerID: func() *string {
			if d.Owner != nil {
				return &d.Owner.Uid
			}
			return nil
		}(),
		Private:   d.Private,
		Processed: d.Processed,
		TakenAt:   d.TakenAt,
		Uid:       d.Uid,
		UploadedByID: func() *string {
			if d.UploadedBy != nil {
				return &d.UploadedBy.Uid
			}
			return nil
		}(),
		Width: d.Width,
	}
}

// APIKey is a GORM entity inferred from dto.APIKey
type APIKey struct {
	ID        uint           `gorm:"primarykey" json:"-"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt time.Time
	UpdatedAt time.Time
	// Description API Key description
	Description *string
	// ExpiresAt Expiry time
	ExpiresAt *time.Time
	// KeyHashed Hashed key
	KeyHashed string
	// LastUsedAt Last used time
	LastUsedAt *time.Time
	// Name API Key name
	Name *string
	// Revoked Is revoked
	Revoked bool
	// RevokedAt Revocation time
	RevokedAt *time.Time
	// Scopes List of scopes
	Scopes []string `gorm:"serializer:json;type:JSONB"`
	// Uid API Key UID
	Uid    string `gorm:"uniqueIndex"`
	UserID *string
	User   *User `gorm:"foreignKey:UserID;references:Uid"`
}

func (e APIKey) DTO() dto.APIKey {
	return dto.APIKey{
		CreatedAt:   e.CreatedAt,
		UpdatedAt:   e.UpdatedAt,
		Description: e.Description,
		ExpiresAt:   e.ExpiresAt,
		KeyHashed:   e.KeyHashed,
		LastUsedAt:  e.LastUsedAt,
		Name:        e.Name,
		Revoked:     e.Revoked,
		RevokedAt:   e.RevokedAt,
		Scopes:      e.Scopes,
		Uid:         e.Uid,
		User: func() *dto.User {
			if e.User != nil {
				d := e.User.DTO()
				return &d
			}
			return nil
		}(),
	}
}

func APIKeyFromDTO(d dto.APIKey) APIKey {
	return APIKey{
		CreatedAt:   d.CreatedAt,
		UpdatedAt:   d.UpdatedAt,
		Description: d.Description,
		ExpiresAt:   d.ExpiresAt,
		KeyHashed:   d.KeyHashed,
		LastUsedAt:  d.LastUsedAt,
		Name:        d.Name,
		Revoked:     d.Revoked,
		RevokedAt:   d.RevokedAt,
		Scopes:      d.Scopes,
		Uid:         d.Uid,
		UserID: func() *string {
			if d.User != nil {
				return &d.User.Uid
			}
			return nil
		}(),
	}
}

// SettingOverride is a GORM entity inferred from dto.SettingOverride
type SettingOverride struct {
	ID        uint           `gorm:"primarykey" json:"-"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt time.Time
	UpdatedAt time.Time
	// Name Links to SettingDefault.name.
	Name string `gorm:"uniqueIndex:idx_setting_overrides_user_name,priority:2"`
	// UserId Links to the users table.
	UserId string `gorm:"uniqueIndex:idx_setting_overrides_user_name,priority:1"`
	// Value The user's chosen value for the setting.
	Value string
}

func (e SettingOverride) DTO() dto.SettingOverride {
	return dto.SettingOverride{
		Name:   e.Name,
		UserId: e.UserId,
		Value:  e.Value,
	}
}

func SettingOverrideFromDTO(d dto.SettingOverride) SettingOverride {
	return SettingOverride{
		Name:   d.Name,
		UserId: d.UserId,
		Value:  d.Value,
	}
}

// User is a GORM entity inferred from dto.User
type User struct {
	ID        uint           `gorm:"primarykey" json:"-"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt time.Time
	UpdatedAt time.Time
	// Email Email
	Email string
	// FirstName First name
	FirstName string
	// LastName Last name
	LastName string
	// Role User role
	Role dto.UserRole `gorm:"type:text"`
	// Uid User UID
	Uid string `gorm:"uniqueIndex"`
	// Username Username
	Username string
}

func (e User) DTO() dto.User {
	return dto.User{
		CreatedAt: e.CreatedAt,
		UpdatedAt: e.UpdatedAt,
		Email:     e.Email,
		FirstName: e.FirstName,
		LastName:  e.LastName,
		Role:      e.Role,
		Uid:       e.Uid,
		Username:  e.Username,
	}
}

func UserFromDTO(d dto.User) User {
	return User{
		CreatedAt: d.CreatedAt,
		UpdatedAt: d.UpdatedAt,
		Email:     d.Email,
		FirstName: d.FirstName,
		LastName:  d.LastName,
		Role:      d.Role,
		Uid:       d.Uid,
		Username:  d.Username,
	}
}

// Session is a GORM entity inferred from dto.Session
type Session struct {
	ID        uint           `gorm:"primarykey" json:"-"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt time.Time
	UpdatedAt time.Time
	// ClientId Client ID
	ClientId *string
	// ClientIp Client IP
	ClientIp *string
	// ClientName Client name
	ClientName *string
	// ExpiresAt Expiry time
	ExpiresAt *time.Time
	// LastActive Last active time
	LastActive *time.Time
	// LoginAt Login time
	LoginAt *time.Time
	// LoginIp Login IP
	LoginIp *string
	// RefId Reference ID
	RefId *string
	// Status Session status
	Status *int
	// Timeout Timeout in seconds
	Timeout *int64
	// Token Session token
	Token string
	// Uid Session UID
	Uid    string `gorm:"uniqueIndex"`
	UserID *string
	User   *User `gorm:"foreignKey:UserID;references:Uid"`
	// UserAgent User agent
	UserAgent *string
	// UserUid User UID
	UserUid string
}

func (e Session) DTO() dto.Session {
	return dto.Session{
		CreatedAt:  e.CreatedAt,
		UpdatedAt:  e.UpdatedAt,
		ClientId:   e.ClientId,
		ClientIp:   e.ClientIp,
		ClientName: e.ClientName,
		ExpiresAt:  e.ExpiresAt,
		LastActive: e.LastActive,
		LoginAt:    e.LoginAt,
		LoginIp:    e.LoginIp,
		RefId:      e.RefId,
		Status:     e.Status,
		Timeout:    e.Timeout,
		Token:      e.Token,
		Uid:        e.Uid,
		User: func() *dto.User {
			if e.User != nil {
				d := e.User.DTO()
				return &d
			}
			return nil
		}(),
		UserAgent: e.UserAgent,
		UserUid:   e.UserUid,
	}
}

func SessionFromDTO(d dto.Session) Session {
	return Session{
		CreatedAt:  d.CreatedAt,
		UpdatedAt:  d.UpdatedAt,
		ClientId:   d.ClientId,
		ClientIp:   d.ClientIp,
		ClientName: d.ClientName,
		ExpiresAt:  d.ExpiresAt,
		LastActive: d.LastActive,
		LoginAt:    d.LoginAt,
		LoginIp:    d.LoginIp,
		RefId:      d.RefId,
		Status:     d.Status,
		Timeout:    d.Timeout,
		Token:      d.Token,
		Uid:        d.Uid,
		UserID: func() *string {
			if d.User != nil {
				return &d.User.Uid
			}
			return nil
		}(),
		UserAgent: d.UserAgent,
		UserUid:   d.UserUid,
	}
}

// CollectionImage is a GORM entity inferred from dto.CollectionImage
type CollectionImage struct {
	ID        uint           `gorm:"primarykey" json:"-"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt time.Time
	UpdatedAt time.Time
	// AddedAt Added timestamp
	AddedAt   time.Time
	AddedByID *string
	AddedBy   *User `gorm:"foreignKey:AddedByID;references:Uid"`
	// Uid Image UID
	Uid string `gorm:"uniqueIndex"`
}

func (e CollectionImage) DTO() dto.CollectionImage {
	return dto.CollectionImage{
		AddedAt: e.AddedAt,
		AddedBy: func() *dto.User {
			if e.AddedBy != nil {
				d := e.AddedBy.DTO()
				return &d
			}
			return nil
		}(),
		Uid: e.Uid,
	}
}

func CollectionImageFromDTO(d dto.CollectionImage) CollectionImage {
	return CollectionImage{
		AddedAt: d.AddedAt,
		AddedByID: func() *string {
			if d.AddedBy != nil {
				return &d.AddedBy.Uid
			}
			return nil
		}(),
		Uid: d.Uid,
	}
}

// CollectionDetailResponse is a GORM entity inferred from dto.CollectionDetailResponse
type CollectionDetailResponse struct {
	ID          uint           `gorm:"primarykey" json:"-"`
	DeletedAt   gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedByID *string
	CreatedBy   *User `gorm:"foreignKey:CreatedByID;references:Uid"`
	// Description Collection description
	Description *string
	// ImageCount Number of images
	ImageCount *int
	Images     dto.ImagesListResponse `gorm:"serializer:json;type:JSONB"`
	// Name Collection name
	Name    string
	OwnerID *string
	Owner   *User `gorm:"foreignKey:OwnerID;references:Uid"`
	// Private Is private
	Private     *bool
	ThumbnailID *string
	Thumbnail   *Image `gorm:"foreignKey:ThumbnailID;references:Uid"`
	// Uid Collection UID
	Uid string `gorm:"uniqueIndex"`
}

func (e CollectionDetailResponse) DTO() dto.CollectionDetailResponse {
	return dto.CollectionDetailResponse{
		CreatedAt: e.CreatedAt,
		UpdatedAt: e.UpdatedAt,
		CreatedBy: func() *dto.User {
			if e.CreatedBy != nil {
				d := e.CreatedBy.DTO()
				return &d
			}
			return nil
		}(),
		Description: e.Description,
		ImageCount:  e.ImageCount,
		Images:      e.Images,
		Name:        e.Name,
		Owner: func() *dto.User {
			if e.Owner != nil {
				d := e.Owner.DTO()
				return &d
			}
			return nil
		}(),
		Private: e.Private,
		Thumbnail: func() *dto.Image {
			if e.Thumbnail != nil {
				d := e.Thumbnail.DTO()
				return &d
			}
			return nil
		}(),
		Uid: e.Uid,
	}
}

func CollectionDetailResponseFromDTO(d dto.CollectionDetailResponse) CollectionDetailResponse {
	return CollectionDetailResponse{
		CreatedAt: d.CreatedAt,
		UpdatedAt: d.UpdatedAt,
		CreatedByID: func() *string {
			if d.CreatedBy != nil {
				return &d.CreatedBy.Uid
			}
			return nil
		}(),
		Description: d.Description,
		ImageCount:  d.ImageCount,
		Images:      d.Images,
		Name:        d.Name,
		OwnerID: func() *string {
			if d.Owner != nil {
				return &d.Owner.Uid
			}
			return nil
		}(),
		Private: d.Private,
		ThumbnailID: func() *string {
			if d.Thumbnail != nil {
				return &d.Thumbnail.Uid
			}
			return nil
		}(),
		Uid: d.Uid,
	}
}

// Collection is a GORM entity inferred from dto.Collection
type Collection struct {
	ID          uint           `gorm:"primarykey" json:"-"`
	DeletedAt   gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedByID *string
	CreatedBy   *User `gorm:"foreignKey:CreatedByID;references:Uid"`
	// Description Collection description
	Description *string
	// Favourited Is favourited
	Favourited *bool
	// ImageCount Number of images
	ImageCount int
	// Images List of images
	Images *[]dto.CollectionImage `gorm:"serializer:json;type:JSONB"`
	// Name Collection name
	Name    string
	OwnerID *string
	Owner   *User `gorm:"foreignKey:OwnerID;references:Uid"`
	// Private Is private
	Private     *bool
	ThumbnailID *string
	Thumbnail   *Image `gorm:"foreignKey:ThumbnailID;references:Uid"`
	// Uid Collection UID
	Uid string `gorm:"uniqueIndex"`
}

func (e Collection) DTO() dto.Collection {
	return dto.Collection{
		CreatedAt: e.CreatedAt,
		UpdatedAt: e.UpdatedAt,
		CreatedBy: func() *dto.User {
			if e.CreatedBy != nil {
				d := e.CreatedBy.DTO()
				return &d
			}
			return nil
		}(),
		Description: e.Description,
		Favourited:  e.Favourited,
		ImageCount:  e.ImageCount,
		Images:      e.Images,
		Name:        e.Name,
		Owner: func() *dto.User {
			if e.Owner != nil {
				d := e.Owner.DTO()
				return &d
			}
			return nil
		}(),
		Private: e.Private,
		Thumbnail: func() *dto.Image {
			if e.Thumbnail != nil {
				d := e.Thumbnail.DTO()
				return &d
			}
			return nil
		}(),
		Uid: e.Uid,
	}
}

func CollectionFromDTO(d dto.Collection) Collection {
	return Collection{
		CreatedAt: d.CreatedAt,
		UpdatedAt: d.UpdatedAt,
		CreatedByID: func() *string {
			if d.CreatedBy != nil {
				return &d.CreatedBy.Uid
			}
			return nil
		}(),
		Description: d.Description,
		Favourited:  d.Favourited,
		ImageCount:  d.ImageCount,
		Images:      d.Images,
		Name:        d.Name,
		OwnerID: func() *string {
			if d.Owner != nil {
				return &d.Owner.Uid
			}
			return nil
		}(),
		Private: d.Private,
		ThumbnailID: func() *string {
			if d.Thumbnail != nil {
				return &d.Thumbnail.Uid
			}
			return nil
		}(),
		Uid: d.Uid,
	}
}

// WorkerJob is a GORM entity inferred from dto.WorkerJob
type WorkerJob struct {
	ID        uint           `gorm:"primarykey" json:"-"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt time.Time
	UpdatedAt time.Time
	// Command Job command
	Command *string
	// CompletedAt Completed timestamp
	CompletedAt *time.Time
	// EnqueuedAt Enqueued timestamp
	EnqueuedAt time.Time
	// ErrorCode Error code if failed
	ErrorCode *string
	// ErrorMsg Error message if failed
	ErrorMsg *string
	// ImageUid Related image UID
	ImageUid *string
	// Payload Job payload
	Payload *string
	// StartedAt Started timestamp
	StartedAt *time.Time
	// Status Job status
	Status string
	// Topic Job topic
	Topic string
	// Type Job type
	Type string
	// Uid Job UID
	Uid string `gorm:"uniqueIndex"`
}

func (e WorkerJob) DTO() dto.WorkerJob {
	return dto.WorkerJob{
		Command:     e.Command,
		CompletedAt: e.CompletedAt,
		EnqueuedAt:  e.EnqueuedAt,
		ErrorCode:   e.ErrorCode,
		ErrorMsg:    e.ErrorMsg,
		ImageUid:    e.ImageUid,
		Payload:     e.Payload,
		StartedAt:   e.StartedAt,
		Status:      e.Status,
		Topic:       e.Topic,
		Type:        e.Type,
		Uid:         e.Uid,
	}
}

func WorkerJobFromDTO(d dto.WorkerJob) WorkerJob {
	return WorkerJob{
		Command:     d.Command,
		CompletedAt: d.CompletedAt,
		EnqueuedAt:  d.EnqueuedAt,
		ErrorCode:   d.ErrorCode,
		ErrorMsg:    d.ErrorMsg,
		ImageUid:    d.ImageUid,
		Payload:     d.Payload,
		StartedAt:   d.StartedAt,
		Status:      d.Status,
		Topic:       d.Topic,
		Type:        d.Type,
		Uid:         d.Uid,
	}
}

// ImageUploadResponse is a GORM entity inferred from dto.ImageUploadResponse
type ImageUploadResponse struct {
	ID        uint           `gorm:"primarykey" json:"-"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt time.Time
	UpdatedAt time.Time
	// Metadata Extracted metadata
	Metadata *map[string]any `gorm:"serializer:json;type:JSONB"`
	// Uid UID of the uploaded image
	Uid string `gorm:"uniqueIndex"`
}

func (e ImageUploadResponse) DTO() dto.ImageUploadResponse {
	return dto.ImageUploadResponse{
		Metadata: e.Metadata,
		Uid:      e.Uid,
	}
}

func ImageUploadResponseFromDTO(d dto.ImageUploadResponse) ImageUploadResponse {
	return ImageUploadResponse{
		Metadata: d.Metadata,
		Uid:      d.Uid,
	}
}
