// Code generated by genentities. DO NOT EDIT.
package entities

import (
	"gorm.io/gorm"
	"imagine/internal/dto"
	"time"
)

// Collection is a GORM entity inferred from dto.Collection
type Collection struct {
	ID          uint           `gorm:"primarykey" json:"-"`
	DeletedAt   gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedByID *string
	CreatedBy   *User `gorm:"foreignKey:CreatedByID;references:Uid"`
	Description *string
	ImageCount  int
	Images      *[]dto.CollectionImage `gorm:"serializer:json;type:JSONB"`
	Name        string
	Private     *bool
	ThumbnailID *string
	Thumbnail   *Image `gorm:"foreignKey:ThumbnailID;references:Uid"`
	Uid         string `gorm:"uniqueIndex"`
}

func (e Collection) DTO() dto.Collection {
	return dto.Collection{
		CreatedAt: e.CreatedAt,
		UpdatedAt: e.UpdatedAt,
		CreatedBy: func() *dto.User {
			if e.CreatedBy != nil {
				d := e.CreatedBy.DTO()
				return &d
			}
			return nil
		}(),
		Description: e.Description,
		ImageCount:  e.ImageCount,
		Images:      e.Images,
		Name:        e.Name,
		Private:     e.Private,
		Thumbnail: func() *dto.Image {
			if e.Thumbnail != nil {
				d := e.Thumbnail.DTO()
				return &d
			}
			return nil
		}(),
		Uid: e.Uid,
	}
}

func CollectionFromDTO(d dto.Collection) Collection {
	return Collection{
		CreatedAt: d.CreatedAt,
		UpdatedAt: d.UpdatedAt,
		CreatedByID: func() *string {
			if d.CreatedBy != nil {
				return &d.CreatedBy.Uid
			}
			return nil
		}(),
		Description: d.Description,
		ImageCount:  d.ImageCount,
		Images:      d.Images,
		Name:        d.Name,
		Private:     d.Private,
		ThumbnailID: func() *string {
			if d.Thumbnail != nil {
				return &d.Thumbnail.Uid
			}
			return nil
		}(),
		Uid: d.Uid,
	}
}

// CollectionDetailResponse is a GORM entity inferred from dto.CollectionDetailResponse
type CollectionDetailResponse struct {
	ID          uint           `gorm:"primarykey" json:"-"`
	DeletedAt   gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedByID *string
	CreatedBy   *User `gorm:"foreignKey:CreatedByID;references:Uid"`
	Description *string
	ImageCount  *int
	Images      dto.ImagesPage `gorm:"serializer:json;type:JSONB"`
	Name        string
	Private     *bool
	ThumbnailID *string
	Thumbnail   *Image `gorm:"foreignKey:ThumbnailID;references:Uid"`
	Uid         string `gorm:"uniqueIndex"`
}

func (e CollectionDetailResponse) DTO() dto.CollectionDetailResponse {
	return dto.CollectionDetailResponse{
		CreatedAt: e.CreatedAt,
		UpdatedAt: e.UpdatedAt,
		CreatedBy: func() *dto.User {
			if e.CreatedBy != nil {
				d := e.CreatedBy.DTO()
				return &d
			}
			return nil
		}(),
		Description: e.Description,
		ImageCount:  e.ImageCount,
		Images:      e.Images,
		Name:        e.Name,
		Private:     e.Private,
		Thumbnail: func() *dto.Image {
			if e.Thumbnail != nil {
				d := e.Thumbnail.DTO()
				return &d
			}
			return nil
		}(),
		Uid: e.Uid,
	}
}

func CollectionDetailResponseFromDTO(d dto.CollectionDetailResponse) CollectionDetailResponse {
	return CollectionDetailResponse{
		CreatedAt: d.CreatedAt,
		UpdatedAt: d.UpdatedAt,
		CreatedByID: func() *string {
			if d.CreatedBy != nil {
				return &d.CreatedBy.Uid
			}
			return nil
		}(),
		Description: d.Description,
		ImageCount:  d.ImageCount,
		Images:      d.Images,
		Name:        d.Name,
		Private:     d.Private,
		ThumbnailID: func() *string {
			if d.Thumbnail != nil {
				return &d.Thumbnail.Uid
			}
			return nil
		}(),
		Uid: d.Uid,
	}
}

// DownloadToken is a GORM entity inferred from dto.DownloadToken
type DownloadToken struct {
	ID            uint           `gorm:"primarykey" json:"-"`
	DeletedAt     gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt     time.Time
	UpdatedAt     time.Time
	AllowDownload bool
	AllowEmbed    bool
	Description   *string
	ExpiresAt     *time.Time
	ImageUids     []string `gorm:"serializer:json;type:JSONB"`
	Password      *string
	ShowMetadata  bool
	Uid           string `gorm:"uniqueIndex"`
}

func (e DownloadToken) DTO() dto.DownloadToken {
	return dto.DownloadToken{
		CreatedAt:     e.CreatedAt,
		UpdatedAt:     e.UpdatedAt,
		AllowDownload: e.AllowDownload,
		AllowEmbed:    e.AllowEmbed,
		Description:   e.Description,
		ExpiresAt:     e.ExpiresAt,
		ImageUids:     e.ImageUids,
		Password:      e.Password,
		ShowMetadata:  e.ShowMetadata,
		Uid:           e.Uid,
	}
}

func DownloadTokenFromDTO(d dto.DownloadToken) DownloadToken {
	return DownloadToken{
		CreatedAt:     d.CreatedAt,
		UpdatedAt:     d.UpdatedAt,
		AllowDownload: d.AllowDownload,
		AllowEmbed:    d.AllowEmbed,
		Description:   d.Description,
		ExpiresAt:     d.ExpiresAt,
		ImageUids:     d.ImageUids,
		Password:      d.Password,
		ShowMetadata:  d.ShowMetadata,
		Uid:           d.Uid,
	}
}

// Image is a GORM entity inferred from dto.Image
type Image struct {
	ID            uint           `gorm:"primarykey" json:"-"`
	DeletedAt     gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Description   *string
	Exif          *dto.ImageEXIF `gorm:"serializer:json;type:JSONB"`
	Height        int32
	ImageMetadata *dto.ImageMetadata `gorm:"serializer:json;type:JSONB"`
	ImagePaths    dto.ImagePaths     `gorm:"serializer:json;type:JSONB"`
	Name          string
	Private       bool
	Processed     bool
	Uid           string `gorm:"uniqueIndex"`
	UploadedByID  *string
	UploadedBy    *User `gorm:"foreignKey:UploadedByID;references:Uid"`
	Width         int32
}

func (e Image) DTO() dto.Image {
	return dto.Image{
		CreatedAt:     e.CreatedAt,
		UpdatedAt:     e.UpdatedAt,
		Description:   e.Description,
		Exif:          e.Exif,
		Height:        e.Height,
	ImageMetadata: e.ImageMetadata,
		ImagePaths:    e.ImagePaths,
		Name:          e.Name,
		Private:       e.Private,
		Processed:     e.Processed,
		Uid:           e.Uid,
		UploadedBy: func() *dto.User {
			if e.UploadedBy != nil {
				d := e.UploadedBy.DTO()
				return &d
			}
			return nil
		}(),
		Width: e.Width,
	}
}

func ImageFromDTO(d dto.Image) Image {
	return Image{
		CreatedAt:     d.CreatedAt,
		UpdatedAt:     d.UpdatedAt,
		Description:   d.Description,
		Exif:          d.Exif,
		Height:        d.Height,
	ImageMetadata: d.ImageMetadata,
		ImagePaths:    d.ImagePaths,
		Name:          d.Name,
		Private:       d.Private,
		Processed:     d.Processed,
		Uid:           d.Uid,
		UploadedByID: func() *string {
			if d.UploadedBy != nil {
				return &d.UploadedBy.Uid
			}
			return nil
		}(),
		Width: d.Width,
	}
}

// Session is a GORM entity inferred from dto.Session
type Session struct {
	ID         uint           `gorm:"primarykey" json:"-"`
	DeletedAt  gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ClientId   *string
	ClientIp   *string
	ClientName *string
	ExpiresAt  *time.Time
	LastActive *time.Time
	LoginAt    *time.Time
	LoginIp    *string
	RefId      *string
	Status     *int
	Timeout    *int64
	Token      string
	Uid        string `gorm:"uniqueIndex"`
	UserID     *string
	User       *User `gorm:"foreignKey:UserID;references:Uid"`
	UserAgent  *string
	UserUid    string
}

func (e Session) DTO() dto.Session {
	return dto.Session{
		CreatedAt:  e.CreatedAt,
		UpdatedAt:  e.UpdatedAt,
		ClientId:   e.ClientId,
		ClientIp:   e.ClientIp,
		ClientName: e.ClientName,
		ExpiresAt:  e.ExpiresAt,
		LastActive: e.LastActive,
		LoginAt:    e.LoginAt,
		LoginIp:    e.LoginIp,
		RefId:      e.RefId,
		Status:     e.Status,
		Timeout:    e.Timeout,
		Token:      e.Token,
		Uid:        e.Uid,
		User: func() *dto.User {
			if e.User != nil {
				d := e.User.DTO()
				return &d
			}
			return nil
		}(),
		UserAgent: e.UserAgent,
		UserUid:   e.UserUid,
	}
}

func SessionFromDTO(d dto.Session) Session {
	return Session{
		CreatedAt:  d.CreatedAt,
		UpdatedAt:  d.UpdatedAt,
		ClientId:   d.ClientId,
		ClientIp:   d.ClientIp,
		ClientName: d.ClientName,
		ExpiresAt:  d.ExpiresAt,
		LastActive: d.LastActive,
		LoginAt:    d.LoginAt,
		LoginIp:    d.LoginIp,
		RefId:      d.RefId,
		Status:     d.Status,
		Timeout:    d.Timeout,
		Token:      d.Token,
		Uid:        d.Uid,
		UserID: func() *string {
			if d.User != nil {
				return &d.User.Uid
			}
			return nil
		}(),
		UserAgent: d.UserAgent,
		UserUid:   d.UserUid,
	}
}

// User is a GORM entity inferred from dto.User
type User struct {
	ID        uint           `gorm:"primarykey" json:"-"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"-"`
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	FirstName string
	LastName  string
	Role      dto.UserRole `gorm:"type:text"`
	Uid       string       `gorm:"uniqueIndex"`
	Username  string
}

func (e User) DTO() dto.User {
	return dto.User{
		CreatedAt: e.CreatedAt,
		UpdatedAt: e.UpdatedAt,
		Email:     e.Email,
		FirstName: e.FirstName,
		LastName:  e.LastName,
		Role:      e.Role,
		Uid:       e.Uid,
		Username:  e.Username,
	}
}

func UserFromDTO(d dto.User) User {
	return User{
		CreatedAt: d.CreatedAt,
		UpdatedAt: d.UpdatedAt,
		Email:     d.Email,
		FirstName: d.FirstName,
		LastName:  d.LastName,
		Role:      d.Role,
		Uid:       d.Uid,
		Username:  d.Username,
	}
}
