package auth

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"math/rand/v2"
	"strings"

	"viz/internal/crypto"
)

func HashSecret(secret string) (string, error) {
	shaHash := sha256.New()
	_, err := shaHash.Write([]byte(secret))

	if err != nil {
		return "", err
	}

	hashedSecret := shaHash.Sum(nil)
	return hex.EncodeToString(hashedSecret), nil
}

func GenerateAPIKey() (map[string]string, error) {
	keyBytes := crypto.MustGenerateRandomBytes(32)

	randomHorseName := strings.ToLower(HorseNames[rand.IntN(len(HorseNames))])
	randomHorseBytes := []byte(randomHorseName)

	// Max length for the horse name bytes should be 24, so any names shorter than that
	// will be filled with randomly generated bytes
	randomHorseBytesGen := crypto.MustGenerateRandomBytes(24 - len(randomHorseBytes))
	randomHorseBytesFilledToMax := append(randomHorseBytes, randomHorseBytesGen...)

	bytesCombined := append(keyBytes, randomHorseBytesFilledToMax...)

	finalConsumerKey := fmt.Sprint(APIKeyPrefix, "_", hex.EncodeToString(bytesCombined))
	hashedKey, _ := HashSecret(finalConsumerKey)

	return map[string]string{
		"consumer_key": finalConsumerKey,
		"hashed_key":   hashedKey,
	}, nil
}
