// Code generated by scripts/js/gen-api.ts. DO NOT EDIT.
package auth

const (
	// AllScope grants permission for *.
	AllScope Scope = "*"
	// AdminReadScope grants permission for admin:read.
	AdminReadScope Scope = "admin:read"
	// AdminWriteScope grants permission for admin:write.
	AdminWriteScope Scope = "admin:write"
	// APIKeysCreateScope grants permission for api-keys:create.
	APIKeysCreateScope Scope = "api-keys:create"
	// APIKeysListScope grants permission for api-keys:list.
	APIKeysListScope Scope = "api-keys:list"
	// APIKeysReadScope grants permission for api-keys:read.
	APIKeysReadScope Scope = "api-keys:read"
	// APIKeysRevokeScope grants permission for api-keys:revoke.
	APIKeysRevokeScope Scope = "api-keys:revoke"
	// APIKeysRotateScope grants permission for api-keys:rotate.
	APIKeysRotateScope Scope = "api-keys:rotate"
	// APIKeysDeleteScope grants permission for api-keys:delete.
	APIKeysDeleteScope Scope = "api-keys:delete"
	// AuthRefreshScope grants permission for auth:refresh.
	AuthRefreshScope Scope = "auth:refresh"
	// AuthRevokeScope grants permission for auth:revoke.
	AuthRevokeScope Scope = "auth:revoke"
	// CollectionsCreateScope grants permission for collections:create.
	CollectionsCreateScope Scope = "collections:create"
	// CollectionsReadScope grants permission for collections:read.
	CollectionsReadScope Scope = "collections:read"
	// CollectionsUpdateScope grants permission for collections:update.
	CollectionsUpdateScope Scope = "collections:update"
	// CollectionsDeleteScope grants permission for collections:delete.
	CollectionsDeleteScope Scope = "collections:delete"
	// CollectionsShareScope grants permission for collections:share.
	CollectionsShareScope Scope = "collections:share"
	// ImagesReadScope grants permission for images:read.
	ImagesReadScope Scope = "images:read"
	// ImagesUploadScope grants permission for images:upload.
	ImagesUploadScope Scope = "images:upload"
	// ImagesUpdateScope grants permission for images:update.
	ImagesUpdateScope Scope = "images:update"
	// ImagesDeleteScope grants permission for images:delete.
	ImagesDeleteScope Scope = "images:delete"
	// ImagesDownloadScope grants permission for images:download.
	ImagesDownloadScope Scope = "images:download"
	// JobsReadScope grants permission for jobs:read.
	JobsReadScope Scope = "jobs:read"
	// JobsCreateScope grants permission for jobs:create.
	JobsCreateScope Scope = "jobs:create"
	// JobsUpdateScope grants permission for jobs:update.
	JobsUpdateScope Scope = "jobs:update"
	// JobsDeleteScope grants permission for jobs:delete.
	JobsDeleteScope Scope = "jobs:delete"
	// UsersCreateScope grants permission for users:create.
	UsersCreateScope Scope = "users:create"
	// UsersReadScope grants permission for users:read.
	UsersReadScope Scope = "users:read"
	// UsersUpdateScope grants permission for users:update.
	UsersUpdateScope Scope = "users:update"
	// UsersDeleteScope grants permission for users:delete.
	UsersDeleteScope Scope = "users:delete"
	// UserSettingsReadScope grants permission for user-settings:read.
	UserSettingsReadScope Scope = "user-settings:read"
	// UserSettingsUpdateScope grants permission for user-settings:update.
	UserSettingsUpdateScope Scope = "user-settings:update"
	// SessionsReadScope grants permission for sessions:read.
	SessionsReadScope Scope = "sessions:read"
	// SessionsUpdateScope grants permission for sessions:update.
	SessionsUpdateScope Scope = "sessions:update"
	// SessionsDeleteScope grants permission for sessions:delete.
	SessionsDeleteScope Scope = "sessions:delete"
	// DownloadsCreateScope grants permission for downloads:create.
	DownloadsCreateScope Scope = "downloads:create"
	// EventsReadScope grants permission for events:read.
	EventsReadScope Scope = "events:read"
)

// AllScopes is a list of all available scopes.
var AllScopes = []ScopeItem{
	{Value: AllScope, Label: "Full Access"},
	{Value: AdminReadScope, Label: "Admin Read"},
	{Value: AdminWriteScope, Label: "Admin Write"},
	{Value: APIKeysCreateScope, Label: "Create API Keys"},
	{Value: APIKeysListScope, Label: "List API Keys"},
	{Value: APIKeysReadScope, Label: "Read API Key"},
	{Value: APIKeysRevokeScope, Label: "Revoke API Keys"},
	{Value: APIKeysRotateScope, Label: "Rotate API Keys"},
	{Value: APIKeysDeleteScope, Label: "Delete API Keys"},
	{Value: AuthRefreshScope, Label: "Refresh Auth"},
	{Value: AuthRevokeScope, Label: "Revoke Auth"},
	{Value: CollectionsCreateScope, Label: "Create Collections"},
	{Value: CollectionsReadScope, Label: "Read Collections"},
	{Value: CollectionsUpdateScope, Label: "Update Collections"},
	{Value: CollectionsDeleteScope, Label: "Delete Collections"},
	{Value: CollectionsShareScope, Label: "Share Collections"},
	{Value: ImagesReadScope, Label: "Read Images"},
	{Value: ImagesUploadScope, Label: "Upload Images"},
	{Value: ImagesUpdateScope, Label: "Update Images"},
	{Value: ImagesDeleteScope, Label: "Delete Images"},
	{Value: ImagesDownloadScope, Label: "Download Images"},
	{Value: JobsReadScope, Label: "Read Jobs"},
	{Value: JobsCreateScope, Label: "Create Jobs"},
	{Value: JobsUpdateScope, Label: "Update Jobs"},
	{Value: JobsDeleteScope, Label: "Delete Jobs"},
	{Value: UsersCreateScope, Label: "Create Users"},
	{Value: UsersReadScope, Label: "Read Users"},
	{Value: UsersUpdateScope, Label: "Update Users"},
	{Value: UsersDeleteScope, Label: "Delete Users"},
	{Value: UserSettingsReadScope, Label: "Read User Settings"},
	{Value: UserSettingsUpdateScope, Label: "Update User Settings"},
	{Value: SessionsReadScope, Label: "Read Sessions"},
	{Value: SessionsUpdateScope, Label: "Update Sessions"},
	{Value: SessionsDeleteScope, Label: "Delete Sessions"},
	{Value: DownloadsCreateScope, Label: "Create Downloads"},
	{Value: EventsReadScope, Label: "Read Events"},
}
