// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package dto

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
	CookieAuthScopes = "CookieAuth.Scopes"
)

// Defines values for AdminUserCreateRole.
const (
	AdminUserCreateRoleAdmin      AdminUserCreateRole = "admin"
	AdminUserCreateRoleGuest      AdminUserCreateRole = "guest"
	AdminUserCreateRoleSuperadmin AdminUserCreateRole = "superadmin"
	AdminUserCreateRoleUser       AdminUserCreateRole = "user"
)

// Defines values for AdminUserUpdateRole.
const (
	AdminUserUpdateRoleAdmin      AdminUserUpdateRole = "admin"
	AdminUserUpdateRoleGuest      AdminUserUpdateRole = "guest"
	AdminUserUpdateRoleSuperadmin AdminUserUpdateRole = "superadmin"
	AdminUserUpdateRoleUser       AdminUserUpdateRole = "user"
)

// Defines values for ImageMetadataLabel.
const (
	ImageMetadataLabelBlue   ImageMetadataLabel = "Blue"
	ImageMetadataLabelGreen  ImageMetadataLabel = "Green"
	ImageMetadataLabelNone   ImageMetadataLabel = "None"
	ImageMetadataLabelOrange ImageMetadataLabel = "Orange"
	ImageMetadataLabelPink   ImageMetadataLabel = "Pink"
	ImageMetadataLabelPurple ImageMetadataLabel = "Purple"
	ImageMetadataLabelRed    ImageMetadataLabel = "Red"
	ImageMetadataLabelYellow ImageMetadataLabel = "Yellow"
)

// Defines values for ImageUpdateImageMetadataLabel.
const (
	ImageUpdateImageMetadataLabelBlue   ImageUpdateImageMetadataLabel = "Blue"
	ImageUpdateImageMetadataLabelGreen  ImageUpdateImageMetadataLabel = "Green"
	ImageUpdateImageMetadataLabelNone   ImageUpdateImageMetadataLabel = "None"
	ImageUpdateImageMetadataLabelOrange ImageUpdateImageMetadataLabel = "Orange"
	ImageUpdateImageMetadataLabelPink   ImageUpdateImageMetadataLabel = "Pink"
	ImageUpdateImageMetadataLabelPurple ImageUpdateImageMetadataLabel = "Purple"
	ImageUpdateImageMetadataLabelRed    ImageUpdateImageMetadataLabel = "Red"
	ImageUpdateImageMetadataLabelYellow ImageUpdateImageMetadataLabel = "Yellow"
)

// Defines values for SettingDefaultValueType.
const (
	Boolean SettingDefaultValueType = "boolean"
	Enum    SettingDefaultValueType = "enum"
	Integer SettingDefaultValueType = "integer"
	Json    SettingDefaultValueType = "json"
	String  SettingDefaultValueType = "string"
)

// Defines values for UserRole.
const (
	UserRoleAdmin      UserRole = "admin"
	UserRoleGuest      UserRole = "guest"
	UserRoleSuperadmin UserRole = "superadmin"
	UserRoleUser       UserRole = "user"
)

// Defines values for WorkerJobCreateRequestCommand.
const (
	All     WorkerJobCreateRequestCommand = "all"
	Missing WorkerJobCreateRequestCommand = "missing"
)

// Defines values for InitiateOAuthParamsProvider.
const (
	InitiateOAuthParamsProviderGithub InitiateOAuthParamsProvider = "github"
	InitiateOAuthParamsProviderGoogle InitiateOAuthParamsProvider = "google"
)

// Defines values for CompleteOAuthParamsProvider.
const (
	CompleteOAuthParamsProviderGithub CompleteOAuthParamsProvider = "github"
	CompleteOAuthParamsProviderGoogle CompleteOAuthParamsProvider = "google"
)

// Defines values for ListImagesParamsSortBy.
const (
	CreatedAt ListImagesParamsSortBy = "created_at"
	Name      ListImagesParamsSortBy = "name"
	TakenAt   ListImagesParamsSortBy = "taken_at"
	UpdatedAt ListImagesParamsSortBy = "updated_at"
)

// Defines values for GetImageFileParamsFormat.
const (
	Avif GetImageFileParamsFormat = "avif"
	Heif GetImageFileParamsFormat = "heif"
	Jpeg GetImageFileParamsFormat = "jpeg"
	Jpg  GetImageFileParamsFormat = "jpg"
	Png  GetImageFileParamsFormat = "png"
	Webp GetImageFileParamsFormat = "webp"
)

// Defines values for GetImageFileParamsDownload.
const (
	N1 GetImageFileParamsDownload = "1"
)

// Defines values for ListJobsParamsStatus.
const (
	Cancelled ListJobsParamsStatus = "cancelled"
	Completed ListJobsParamsStatus = "completed"
	Failed    ListJobsParamsStatus = "failed"
	Queued    ListJobsParamsStatus = "queued"
	Running   ListJobsParamsStatus = "running"
)

// APIKey defines model for APIKey.
type APIKey struct {
	// CreatedAt Creation time
	CreatedAt time.Time `json:"created_at"`

	// Description API Key description
	Description *string `json:"description"`

	// ExpiresAt Expiry time
	ExpiresAt *time.Time `json:"expires_at"`

	// KeyHashed Hashed key
	KeyHashed string `json:"key_hashed"`

	// LastUsedAt Last used time
	LastUsedAt *time.Time `json:"last_used_at"`

	// Name API Key name
	Name *string `json:"name,omitempty"`

	// Revoked Is revoked
	Revoked bool `json:"revoked"`

	// RevokedAt Revocation time
	RevokedAt *time.Time `json:"revoked_at,omitempty"`

	// Scopes List of scopes
	Scopes []string `json:"scopes"`

	// Uid API Key UID
	Uid string `json:"uid"`

	// UpdatedAt Update time
	UpdatedAt time.Time `json:"updated_at"`
	User      *User     `json:"user,omitempty"`
}

// APIKeyCreate defines model for APIKeyCreate.
type APIKeyCreate struct {
	// Description API Key description
	Description *string `json:"description"`

	// ExpiresAt Expiry time
	ExpiresAt *time.Time `json:"expires_at"`

	// Name API Key name
	Name *string `json:"name,omitempty"`

	// Scopes List of scopes
	Scopes *[]string `json:"scopes,omitempty"`
}

// APIKeyCreateResponse defines model for APIKeyCreateResponse.
type APIKeyCreateResponse struct {
	// ConsumerKey The consumer key (secret)
	ConsumerKey string `json:"consumer_key"`

	// ExpiresAt Expiry time
	ExpiresAt *time.Time `json:"expires_at"`
}

// APIKeyListResponse defines model for APIKeyListResponse.
type APIKeyListResponse struct {
	// Count Total count
	Count int `json:"count"`

	// Items List of API keys
	Items []APIKey `json:"items"`
}

// AddImagesResponse defines model for AddImagesResponse.
type AddImagesResponse struct {
	// Added Whether images were added
	Added bool `json:"added"`

	// Error Error message if failed
	Error *string `json:"error,omitempty"`
}

// AdminUserCreate defines model for AdminUserCreate.
type AdminUserCreate struct {
	// Email User's email address
	Email openapi_types.Email `json:"email"`

	// Name User's full name
	Name string `json:"name"`

	// Password User's password
	Password string `json:"password"`

	// Role User role
	Role *AdminUserCreateRole `json:"role,omitempty"`
}

// AdminUserCreateRole User role
type AdminUserCreateRole string

// AdminUserUpdate defines model for AdminUserUpdate.
type AdminUserUpdate struct {
	// Email Email address
	Email *openapi_types.Email `json:"email"`

	// FirstName First name
	FirstName *string `json:"first_name"`

	// LastName Last name
	LastName *string `json:"last_name"`

	// Role User role
	Role *AdminUserUpdateRole `json:"role"`

	// Username Username
	Username *string `json:"username"`
}

// AdminUserUpdateRole User role
type AdminUserUpdateRole string

// CacheConfig defines model for CacheConfig.
type CacheConfig struct {
	// GcEnabled GC enabled
	GcEnabled *bool `json:"gc_enabled,omitempty"`
}

// CacheStatusResponse defines model for CacheStatusResponse.
type CacheStatusResponse struct {
	// HitRatio Cache hit ratio
	HitRatio float32 `json:"hit_ratio"`

	// Hits Number of cache hits
	Hits int `json:"hits"`

	// Items Number of items currently in the cache
	Items int `json:"items"`

	// Misses Number of cache misses
	Misses int `json:"misses"`

	// Size Current size of the cache in bytes
	Size int `json:"size"`
}

// Collection defines model for Collection.
type Collection struct {
	// CreatedAt Creation time
	CreatedAt time.Time `json:"created_at"`
	CreatedBy *User     `json:"created_by,omitempty"`

	// Description Collection description
	Description *string `json:"description,omitempty"`

	// Favourited Is favourited
	Favourited *bool `json:"favourited,omitempty"`

	// ImageCount Number of images
	ImageCount int `json:"image_count"`

	// Images List of images
	Images *[]CollectionImage `json:"images,omitempty"`

	// Name Collection name
	Name  string `json:"name"`
	Owner *User  `json:"owner,omitempty"`

	// Private Is private
	Private   *bool  `json:"private"`
	Thumbnail *Image `json:"thumbnail,omitempty"`

	// Uid Collection UID
	Uid string `json:"uid"`

	// UpdatedAt Update time
	UpdatedAt time.Time `json:"updated_at"`
}

// CollectionCreate defines model for CollectionCreate.
type CollectionCreate struct {
	// Description Collection description
	Description *string `json:"description,omitempty"`

	// Name Collection name
	Name string `json:"name"`

	// Private Is private
	Private *bool `json:"private"`
}

// CollectionDetailResponse defines model for CollectionDetailResponse.
type CollectionDetailResponse struct {
	// CreatedAt Creation time
	CreatedAt time.Time `json:"created_at"`
	CreatedBy *User     `json:"created_by,omitempty"`

	// Description Collection description
	Description *string `json:"description,omitempty"`

	// ImageCount Number of images
	ImageCount *int               `json:"image_count,omitempty"`
	Images     ImagesListResponse `json:"images"`

	// Name Collection name
	Name  string `json:"name"`
	Owner *User  `json:"owner,omitempty"`

	// Private Is private
	Private   *bool  `json:"private"`
	Thumbnail *Image `json:"thumbnail,omitempty"`

	// Uid Collection UID
	Uid string `json:"uid"`

	// UpdatedAt Update time
	UpdatedAt time.Time `json:"updated_at"`
}

// CollectionImage defines model for CollectionImage.
type CollectionImage struct {
	// AddedAt Added timestamp
	AddedAt time.Time `json:"added_at"`
	AddedBy *User     `json:"added_by,omitempty"`

	// Uid Image UID
	Uid string `json:"uid"`
}

// CollectionListResponse defines model for CollectionListResponse.
type CollectionListResponse struct {
	// Count Total count
	Count *int `json:"count,omitempty"`

	// Href Self link
	Href *string `json:"href,omitempty"`

	// Items List of collections
	Items []Collection `json:"items"`

	// Limit Items per page
	Limit int `json:"limit"`

	// Next Next page link
	Next *string `json:"next,omitempty"`

	// Page Current page
	Page int `json:"page"`

	// Prev Previous page link
	Prev *string `json:"prev,omitempty"`
}

// CollectionUpdate defines model for CollectionUpdate.
type CollectionUpdate struct {
	// Description Collection description
	Description *string `json:"description,omitempty"`

	// Favourited Is favourited
	Favourited *bool `json:"favourited,omitempty"`

	// Name Collection name
	Name *string `json:"name,omitempty"`

	// OwnerUID Owner UID
	OwnerUID *string `json:"ownerUID,omitempty"`

	// Private Is private
	Private *bool `json:"private,omitempty"`

	// ThumbnailUID Thumbnail image UID
	ThumbnailUID *string `json:"thumbnailUID,omitempty"`
}

// DatabaseConfig defines model for DatabaseConfig.
type DatabaseConfig struct {
	// Location Database location/host
	Location *string `json:"location,omitempty"`

	// Name Database name
	Name *string `json:"name,omitempty"`

	// Password Masked password
	Password *string `json:"password,omitempty"`

	// Port Database port
	Port *int `json:"port,omitempty"`

	// User Database user
	User *string `json:"user,omitempty"`
}

// DatabaseStatsResponse defines model for DatabaseStatsResponse.
type DatabaseStatsResponse struct {
	// ActiveConnections Number of active connections (Postgres only)
	ActiveConnections *int64 `json:"active_connections,omitempty"`

	// CollectionCount Total number of collections
	CollectionCount int64 `json:"collection_count"`

	// DbSizeBytes Size of the database in bytes (Postgres only)
	DbSizeBytes *int64 `json:"db_size_bytes,omitempty"`

	// ImageCount Total number of images
	ImageCount int64 `json:"image_count"`

	// UserCount Total number of users
	UserCount int64 `json:"user_count"`
}

// DeleteAssetsResponse defines model for DeleteAssetsResponse.
type DeleteAssetsResponse struct {
	// Results Results of deletion
	Results *[]struct {
		// Deleted Whether it was deleted
		Deleted *bool `json:"deleted,omitempty"`

		// Error Error message if failed
		Error *string `json:"error,omitempty"`

		// Uid UID of the asset
		Uid *string `json:"uid,omitempty"`
	} `json:"results,omitempty"`
}

// DeleteImagesResponse defines model for DeleteImagesResponse.
type DeleteImagesResponse struct {
	// Deleted Whether images were deleted
	Deleted bool `json:"deleted"`

	// Error Error message if failed
	Error *string `json:"error,omitempty"`
}

// DownloadRequest defines model for DownloadRequest.
type DownloadRequest struct {
	// FileName Desired filename for the archive
	FileName *string `json:"file_name,omitempty"`

	// Uids List of UIDs to download
	Uids []string `json:"uids"`
}

// DownloadToken Persistent download token with granular access controls
type DownloadToken struct {
	// AllowDownload Whether downloads are permitted with this token
	AllowDownload bool `json:"allow_download"`

	// AllowEmbed Whether embedding on external sites is allowed (false prevents hotlinking)
	AllowEmbed bool `json:"allow_embed"`

	// CreatedAt When this token was created
	CreatedAt time.Time `json:"created_at"`

	// Description Optional description of this download link
	Description *string `json:"description"`

	// ExpiresAt When this token expires (null for no expiry)
	ExpiresAt *time.Time `json:"expires_at"`

	// ImageUids Array of authorized image UIDs
	ImageUids []string `json:"image_uids"`

	// Password Optional bcrypt hash of password (null if no password protection)
	Password *string `json:"password"`

	// ShowMetadata Whether to include EXIF and metadata in responses
	ShowMetadata bool `json:"show_metadata"`

	// Uid 64-character hex token that serves as both unique identifier and authorization key
	Uid string `json:"uid"`

	// UpdatedAt When this token was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Error message
	Error string `json:"error"`
}

// EventHistoryResponse defines model for EventHistoryResponse.
type EventHistoryResponse struct {
	// Count Count of events returned
	Count int `json:"count"`

	// Events List of historical events
	Events []EventRecord `json:"events"`
}

// EventRecord defines model for EventRecord.
type EventRecord struct {
	// Data Event data payload
	Data map[string]interface{} `json:"data"`

	// Event Event name
	Event string `json:"event"`

	// Timestamp Event timestamp
	Timestamp time.Time `json:"timestamp"`
}

// Image defines model for Image.
type Image struct {
	// CreatedAt Creation time
	CreatedAt time.Time `json:"created_at"`

	// Description Image description
	Description *string    `json:"description,omitempty"`
	Exif        *ImageEXIF `json:"exif,omitempty"`

	// Favourited Is favourited
	Favourited *bool `json:"favourited,omitempty"`

	// Height Image height
	Height        int32          `json:"height"`
	ImageMetadata *ImageMetadata `json:"image_metadata,omitempty"`
	ImagePaths    ImagePaths     `json:"image_paths"`

	// Name Image name
	Name  string `json:"name"`
	Owner *User  `json:"owner,omitempty"`

	// Private Is private
	Private bool `json:"private"`

	// Processed Is processed
	Processed bool `json:"processed"`

	// TakenAt Taken time
	TakenAt *time.Time `json:"taken_at"`

	// Uid Image UID
	Uid string `json:"uid"`

	// UpdatedAt Update time
	UpdatedAt  time.Time `json:"updated_at"`
	UploadedBy *User     `json:"uploaded_by,omitempty"`

	// Width Image width
	Width int32 `json:"width"`
}

// ImageEXIF defines model for ImageEXIF.
type ImageEXIF struct {
	// Aperture Aperture
	Aperture *string `json:"aperture,omitempty"`

	// Copyright Copyright
	Copyright *string `json:"copyright,omitempty"`

	// DateTime Date and time
	DateTime *string `json:"date_time,omitempty"`

	// DateTimeOriginal Original date and time
	DateTimeOriginal *string `json:"date_time_original,omitempty"`

	// DigitalZoomRatio Digital zoom ratio
	DigitalZoomRatio *string `json:"digital_zoom_ratio,omitempty"`

	// ExifVersion EXIF version
	ExifVersion *string `json:"exif_version,omitempty"`

	// ExposureBiasValue Exposure bias value
	ExposureBiasValue *string `json:"exposure_bias_value,omitempty"`

	// ExposureMode Exposure mode
	ExposureMode *string `json:"exposure_mode,omitempty"`

	// ExposureProgram Exposure program
	ExposureProgram *string `json:"exposure_program,omitempty"`

	// ExposureTime Exposure time
	ExposureTime *string `json:"exposure_time,omitempty"`

	// ExposureValue Exposure value
	ExposureValue *string `json:"exposure_value,omitempty"`

	// FNumber F-number
	FNumber *string `json:"f_number,omitempty"`

	// Flash Flash fired
	Flash *int `json:"flash,omitempty"`

	// FocalLength Focal length
	FocalLength *string `json:"focal_length,omitempty"`

	// FocalLengthIn35mmFormat Focal length in 35mm format
	FocalLengthIn35mmFormat *string `json:"focal_length_in_35mm_format,omitempty"`

	// FocalPlaneResolutionUnit Focal plane resolution unit
	FocalPlaneResolutionUnit *string `json:"focal_plane_resolution_unit,omitempty"`

	// FocalPlaneXResolution Focal plane X resolution
	FocalPlaneXResolution *string `json:"focal_plane_x_resolution,omitempty"`

	// FocalPlaneYResolution Focal plane Y resolution
	FocalPlaneYResolution *string `json:"focal_plane_y_resolution,omitempty"`

	// GpsAltitude GPS Altitude
	GpsAltitude *string `json:"gps_altitude,omitempty"`

	// GpsImgDirection GPS Image Direction
	GpsImgDirection *string `json:"gps_img_direction,omitempty"`

	// GpsImgDirectionRef GPS Image Direction Ref
	GpsImgDirectionRef *string `json:"gps_img_direction_ref,omitempty"`

	// GpsSpeed GPS Speed
	GpsSpeed *string `json:"gps_speed,omitempty"`

	// GpsSpeedRef GPS Speed Ref
	GpsSpeedRef *string `json:"gps_speed_ref,omitempty"`

	// Iso ISO speed rating
	Iso *string `json:"iso,omitempty"`

	// Latitude GPS Latitude
	Latitude *string `json:"latitude,omitempty"`

	// LensMake Lens make
	LensMake *string `json:"lens_make,omitempty"`

	// LensModel Lens model
	LensModel *string `json:"lens_model,omitempty"`

	// LightSource Light source
	LightSource *string `json:"light_source,omitempty"`

	// Longitude GPS Longitude
	Longitude *string `json:"longitude,omitempty"`

	// Make Camera make
	Make *string `json:"make,omitempty"`

	// MaxApertureValue Max aperture value
	MaxApertureValue *string `json:"max_aperture_value,omitempty"`

	// MeteringMode Metering mode
	MeteringMode *string `json:"metering_mode,omitempty"`

	// Model Camera model
	Model *string `json:"model,omitempty"`

	// ModifyDate Modify date
	ModifyDate *string `json:"modify_date,omitempty"`

	// OffsetTime Offset time
	OffsetTime *string `json:"offset_time,omitempty"`

	// OffsetTimeDigitized Offset time digitized
	OffsetTimeDigitized *string `json:"offset_time_digitized,omitempty"`

	// OffsetTimeOriginal Offset time original
	OffsetTimeOriginal *string `json:"offset_time_original,omitempty"`

	// Orientation Orientation
	Orientation *string `json:"orientation,omitempty"`

	// Rating Rating
	Rating *string `json:"rating,omitempty"`

	// Resolution Resolution
	Resolution *string `json:"resolution,omitempty"`

	// SceneCaptureType Scene capture type
	SceneCaptureType *string `json:"scene_capture_type,omitempty"`

	// SensingMethod Sensing method
	SensingMethod *string `json:"sensing_method,omitempty"`

	// Software Software
	Software *string `json:"software,omitempty"`

	// WhiteBalance White balance
	WhiteBalance *string `json:"white_balance,omitempty"`
}

// ImageMetadata defines model for ImageMetadata.
type ImageMetadata struct {
	// Checksum File checksum
	Checksum string `json:"checksum"`

	// ColorSpace Color space
	ColorSpace string `json:"color_space"`

	// FileCreatedAt File creation time
	FileCreatedAt time.Time `json:"file_created_at"`

	// FileModifiedAt File modification time
	FileModifiedAt time.Time `json:"file_modified_at"`

	// FileName Original file name
	FileName string `json:"file_name"`

	// FileSize File size in bytes
	FileSize *int64 `json:"file_size,omitempty"`

	// FileType File MIME type
	FileType string `json:"file_type"`

	// HasIccProfile Has ICC profile
	HasIccProfile *bool `json:"has_icc_profile,omitempty"`

	// Keywords Keywords
	Keywords *[]string `json:"keywords,omitempty"`

	// Label User-assigned label for the image. Null = unlabeled
	Label *ImageMetadataLabel `json:"label"`

	// Metadata Additional metadata
	Metadata *string `json:"metadata,omitempty"`

	// OriginalFileName Original file name
	OriginalFileName *string `json:"original_file_name,omitempty"`

	// Rating User-assigned rating (0-5). Null = unrated
	Rating *int `json:"rating"`

	// Thumbhash Thumbhash
	Thumbhash *string `json:"thumbhash,omitempty"`
}

// ImageMetadataLabel User-assigned label for the image. Null = unlabeled
type ImageMetadataLabel string

// ImagePaths defines model for ImagePaths.
type ImagePaths struct {
	// Original Path to original file
	Original string `json:"original"`

	// Preview Path to preview
	Preview string `json:"preview"`

	// Raw Path to raw file
	Raw *string `json:"raw,omitempty"`

	// Thumbnail Path to thumbnail
	Thumbnail string `json:"thumbnail"`
}

// ImageUpdate defines model for ImageUpdate.
type ImageUpdate struct {
	// Description Image description
	Description *string    `json:"description"`
	Exif        *ImageEXIF `json:"exif,omitempty"`

	// Favourited Is favourited
	Favourited    *bool `json:"favourited,omitempty"`
	ImageMetadata *struct {
		// Keywords Keywords
		Keywords *[]string `json:"keywords,omitempty"`

		// Label User-assigned label for the image. Null = unlabeled
		Label *ImageUpdateImageMetadataLabel `json:"label"`

		// Rating User-assigned rating (0-5). Null = unrated
		Rating *int `json:"rating"`
	} `json:"image_metadata,omitempty"`

	// Name Image name
	Name *string `json:"name,omitempty"`

	// OwnerUid Owner UID
	OwnerUid *string `json:"owner_uid"`

	// Private Is private
	Private *bool `json:"private,omitempty"`
}

// ImageUpdateImageMetadataLabel User-assigned label for the image. Null = unlabeled
type ImageUpdateImageMetadataLabel string

// ImageUploadRequest defines model for ImageUploadRequest.
type ImageUploadRequest struct {
	// Checksum Optional checksum of the file
	Checksum *string `json:"checksum,omitempty"`

	// Data Image file data
	Data openapi_types.File `json:"data"`

	// FileName Name of the file
	FileName string `json:"file_name"`
}

// ImageUploadResponse defines model for ImageUploadResponse.
type ImageUploadResponse struct {
	// Metadata Extracted metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Uid UID of the uploaded image
	Uid string `json:"uid"`
}

// ImagesListResponse defines model for ImagesListResponse.
type ImagesListResponse struct {
	// Count Total count
	Count *int `json:"count,omitempty"`

	// Href Self link
	Href *string `json:"href,omitempty"`

	// Items List of items
	Items []ImagesResponse `json:"items"`

	// Limit Items per page
	Limit int `json:"limit"`

	// Next Next page link
	Next *string `json:"next,omitempty"`

	// Page Current page
	Page int `json:"page"`

	// Prev Previous page link
	Prev *string `json:"prev,omitempty"`
}

// ImagesResponse defines model for ImagesResponse.
type ImagesResponse struct {
	// AddedAt Added timestamp
	AddedAt time.Time `json:"added_at"`
	AddedBy *User     `json:"added_by,omitempty"`
	Image   Image     `json:"image"`
}

// ImagineConfig defines model for ImagineConfig.
type ImagineConfig struct {
	// BaseUrl Base URL of the application
	BaseUrl *string `json:"baseUrl,omitempty"`

	// BaseDirectory Base directory path
	BaseDirectory  *string               `json:"base_directory,omitempty"`
	Cache          *CacheConfig          `json:"cache,omitempty"`
	Database       *DatabaseConfig       `json:"database,omitempty"`
	Libvips        *LibvipsConfig        `json:"libvips,omitempty"`
	Logging        *LoggingConfig        `json:"logging,omitempty"`
	Redis          *QueueConfig          `json:"redis,omitempty"`
	StorageMetrics *StorageMetricsConfig `json:"storage_metrics,omitempty"`
	Upload         *UploadConfig         `json:"upload,omitempty"`
	UserManagement *UserManagementConfig `json:"user_management,omitempty"`
}

// LibvipsConfig defines model for LibvipsConfig.
type LibvipsConfig struct {
	// CacheMaxFiles Cache max files
	CacheMaxFiles *int `json:"cache_max_files,omitempty"`

	// CacheMaxMemoryMb Cache max memory MB
	CacheMaxMemoryMb *int `json:"cache_max_memory_mb,omitempty"`

	// CacheMaxOperations Cache max operations
	CacheMaxOperations *int `json:"cache_max_operations,omitempty"`

	// Concurrency Concurrency level
	Concurrency *int `json:"concurrency,omitempty"`

	// MatchSystemLogging Match system logging level
	MatchSystemLogging *bool `json:"match_system_logging,omitempty"`

	// VectorEnabled Vector enabled
	VectorEnabled *bool `json:"vector_enabled,omitempty"`
}

// LoggingConfig defines model for LoggingConfig.
type LoggingConfig struct {
	// Level Logging level
	Level *string `json:"level,omitempty"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	// Message Response message
	Message string `json:"message"`
}

// OAuthUserData defines model for OAuthUserData.
type OAuthUserData struct {
	// Email User email
	Email openapi_types.Email `json:"email"`

	// Name User name
	Name string `json:"name"`

	// Picture User profile picture URL
	Picture string `json:"picture"`
}

// QueueConfig defines model for QueueConfig.
type QueueConfig struct {
	// Db Redis DB index
	Db *int `json:"db,omitempty"`

	// DialTimeoutSeconds Dial timeout
	DialTimeoutSeconds *int `json:"dial_timeout_seconds,omitempty"`

	// Enabled Is queue enabled
	Enabled *bool `json:"enabled,omitempty"`

	// Host Queue host
	Host *string `json:"host,omitempty"`

	// Password Masked password
	Password *string `json:"password,omitempty"`

	// PoolSize Connection pool size
	PoolSize *int `json:"pool_size,omitempty"`

	// Port Queue port
	Port *int `json:"port,omitempty"`

	// ReadTimeoutSeconds Read timeout
	ReadTimeoutSeconds *int `json:"read_timeout_seconds,omitempty"`

	// UseTls Use TLS
	UseTls *bool `json:"use_tls,omitempty"`

	// Username Queue username
	Username *string `json:"username,omitempty"`

	// WriteTimeoutSeconds Write timeout
	WriteTimeoutSeconds *int `json:"write_timeout_seconds,omitempty"`
}

// SearchListResponse defines model for SearchListResponse.
type SearchListResponse struct {
	// Collections List of collections found
	Collections []Collection `json:"collections"`

	// Images List of images found
	Images []Image `json:"images"`
}

// Session defines model for Session.
type Session struct {
	// ClientId Client ID
	ClientId *string `json:"client_id,omitempty"`

	// ClientIp Client IP
	ClientIp *string `json:"client_ip,omitempty"`

	// ClientName Client name
	ClientName *string `json:"client_name,omitempty"`

	// CreatedAt Creation time
	CreatedAt time.Time `json:"created_at"`

	// ExpiresAt Expiry time
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// LastActive Last active time
	LastActive *time.Time `json:"last_active,omitempty"`

	// LoginAt Login time
	LoginAt *time.Time `json:"login_at,omitempty"`

	// LoginIp Login IP
	LoginIp *string `json:"login_ip,omitempty"`

	// RefId Reference ID
	RefId *string `json:"ref_id,omitempty"`

	// Status Session status
	Status *int `json:"status,omitempty"`

	// Timeout Timeout in seconds
	Timeout *int64 `json:"timeout,omitempty"`

	// Token Session token
	Token string `json:"token"`

	// Uid Session UID
	Uid string `json:"uid"`

	// UpdatedAt Update time
	UpdatedAt time.Time `json:"updated_at"`
	User      *User     `json:"user,omitempty"`

	// UserAgent User agent
	UserAgent *string `json:"user_agent,omitempty"`

	// UserUid User UID
	UserUid string `json:"user_uid"`
}

// SessionUpdate defines model for SessionUpdate.
type SessionUpdate struct {
	// ClientName New client name
	ClientName *string `json:"clientName"`

	// Status New status
	Status *int `json:"status"`
}

// SettingDefault Defines a setting available in the system.
type SettingDefault struct {
	// AllowedValues List of valid choices if type is enum.
	AllowedValues *[]string `json:"allowed_values"`

	// Description Description for UI
	Description string `json:"description"`

	// DisplayName A readable and UI-friendly name for the setting (not required but highly recommended).
	DisplayName string `json:"display_name"`

	// Group Category/group for the setting (e.g., General, Notifications).
	Group string `json:"group"`

	// IsUserEditable Describes whether a user can edit this setting.
	IsUserEditable bool `json:"is_user_editable"`

	// Name Unique name for the setting (primary key).
	Name string `json:"name"`

	// Value The default value everyone gets.
	Value string `json:"value"`

	// ValueType Data type of the setting.
	ValueType SettingDefaultValueType `json:"value_type"`
}

// SettingDefaultValueType Data type of the setting.
type SettingDefaultValueType string

// SettingOverride Stores user-specific changes to settings.
type SettingOverride struct {
	// Name Links to SettingDefault.name.
	Name string `json:"name"`

	// UserId Links to the users table.
	UserId string `json:"user_id"`

	// Value The user's chosen value for the setting.
	Value string `json:"value"`
}

// SignDownloadRequest Request to create a download token
type SignDownloadRequest struct {
	// AllowDownload Allow downloads using this token (default true)
	AllowDownload *bool `json:"allow_download,omitempty"`

	// AllowEmbed Allow embedding images on external sites (default false to prevent hotlinking)
	AllowEmbed *bool `json:"allow_embed,omitempty"`

	// Description Optional description of this share/download link
	Description *string `json:"description,omitempty"`

	// ExpiresIn Time in seconds until the token expires (0 for no expiry, default 900 = 15 minutes)
	ExpiresIn *int `json:"expires_in,omitempty"`

	// Password Optional password protection for the token (will be bcrypt hashed)
	Password *string `json:"password,omitempty"`

	// ShowMetadata Include EXIF and other metadata in responses (default true)
	ShowMetadata *bool `json:"show_metadata,omitempty"`

	// Uids Array of image UIDs to include in the download token
	Uids *[]string `json:"uids,omitempty"`
}

// StorageMetricsConfig defines model for StorageMetricsConfig.
type StorageMetricsConfig struct {
	// Enabled Metrics enabled
	Enabled *bool `json:"enabled,omitempty"`

	// IntervalSeconds Interval in seconds
	IntervalSeconds *int `json:"interval_seconds,omitempty"`
}

// SuperadminSetupRequest defines model for SuperadminSetupRequest.
type SuperadminSetupRequest struct {
	// Email Email address
	Email openapi_types.Email `json:"email"`

	// FirstName First name
	FirstName *string `json:"firstName"`

	// LastName Last name
	LastName *string `json:"lastName"`

	// Password Password
	Password string `json:"password"`

	// Username Desired username
	Username string `json:"username"`
}

// SuperadminSetupResponse defines model for SuperadminSetupResponse.
type SuperadminSetupResponse struct {
	// Message Response message
	Message string `json:"message"`

	// SessionToken Session token for the newly created superadmin
	SessionToken string `json:"sessionToken"`
	User         User   `json:"user"`
}

// SystemStatsResponse defines model for SystemStatsResponse.
type SystemStatsResponse struct {
	// AllocMemory Bytes of allocated heap objects
	AllocMemory int64 `json:"alloc_memory"`

	// NumGoroutine Number of running goroutines
	NumGoroutine int `json:"num_goroutine"`

	// StoragePath Path to storage directory
	StoragePath string `json:"storage_path"`

	// StorageUsedBytes Total size of files in the base directory
	StorageUsedBytes int64 `json:"storage_used_bytes"`

	// SysMemory Total bytes of memory obtained from the OS
	SysMemory int64 `json:"sys_memory"`

	// TotalAvailableSpaceBytes Total available disk space on the system
	TotalAvailableSpaceBytes int64 `json:"total_available_space_bytes"`

	// TotalSystemSpaceBytes Total disk space on the system
	TotalSystemSpaceBytes int64 `json:"total_system_space_bytes"`

	// UptimeSeconds System uptime in seconds
	UptimeSeconds int64 `json:"uptime_seconds"`
}

// SystemStatusResponse defines model for SystemStatusResponse.
type SystemStatusResponse struct {
	// AllowManualRegistration True if user registration is enabled, let's users register accounts themselves
	AllowManualRegistration bool `json:"allow_manual_registration"`

	// Initialized True if the system has been initialized (at least one superadmin exists and first_run_complete is true).
	Initialized bool `json:"initialized"`

	// NeedsSuperadmin True if the system requires initial superadmin setup (no superadmin exists).
	NeedsSuperadmin bool `json:"needs_superadmin"`

	// UserOnboardingRequired True if the current user (if authenticated) still needs to complete onboarding.
	UserOnboardingRequired bool `json:"user_onboarding_required"`
}

// UploadConfig defines model for UploadConfig.
type UploadConfig struct {
	// Location Upload location
	Location *string `json:"location,omitempty"`
}

// User defines model for User.
type User struct {
	// CreatedAt Creation time
	CreatedAt time.Time `json:"created_at"`

	// Email Email
	Email string `json:"email"`

	// FirstName First name
	FirstName string `json:"first_name"`

	// LastName Last name
	LastName string `json:"last_name"`

	// Role User role
	Role UserRole `json:"role"`

	// Uid User UID
	Uid string `json:"uid"`

	// UpdatedAt Update time
	UpdatedAt time.Time `json:"updated_at"`

	// Username Username
	Username string `json:"username"`
}

// UserRole User role
type UserRole string

// UserCreate defines model for UserCreate.
type UserCreate struct {
	// Email Email address
	Email openapi_types.Email `json:"email"`

	// Name Full name
	Name string `json:"name"`

	// Password Password
	Password string `json:"password"`
}

// UserManagementConfig defines model for UserManagementConfig.
type UserManagementConfig struct {
	// AllowManualRegistration Allow manual registration
	AllowManualRegistration *bool `json:"allow_manual_registration,omitempty"`
}

// UserOnboardingBody defines model for UserOnboardingBody.
type UserOnboardingBody struct {
	// FirstName First name
	FirstName string `json:"first_name"`

	// LastName Last name
	LastName string `json:"last_name"`

	// Settings User-specific setting overrides
	Settings []UserSetting `json:"settings"`
}

// UserPasswordUpdate defines model for UserPasswordUpdate.
type UserPasswordUpdate struct {
	// Current Current password
	Current string `json:"current"`

	// New New password
	New string `json:"new"`
}

// UserSetting The effective setting for a user (merged Default and Override).
type UserSetting struct {
	// AllowedValues Allowed values if enum
	AllowedValues *[]string `json:"allowed_values"`

	// DefaultValue Default value
	DefaultValue string `json:"default_value"`

	// Description Setting description
	Description string `json:"description"`

	// DisplayName Readable name
	DisplayName string `json:"display_name"`

	// Group Setting group
	Group string `json:"group"`

	// IsUserEditable Whether user can edit
	IsUserEditable *bool `json:"is_user_editable,omitempty"`

	// Name Setting unique name
	Name string `json:"name"`

	// Value The effective value (override if exists, else default).
	Value string `json:"value"`

	// ValueType Type of the value
	ValueType string `json:"value_type"`
}

// UserSettingUpdateRequest defines model for UserSettingUpdateRequest.
type UserSettingUpdateRequest struct {
	// Settings List of settings to update
	Settings []struct {
		// Name Setting name
		Name string `json:"name"`

		// Value Setting value
		Value string `json:"value"`
	} `json:"settings"`
}

// UserUpdate defines model for UserUpdate.
type UserUpdate struct {
	// Email Email address
	Email *openapi_types.Email `json:"email"`

	// FirstName First name
	FirstName *string `json:"first_name"`

	// LastName Last name
	LastName *string `json:"last_name"`

	// Username Username
	Username *string `json:"username"`
}

// WSBroadcastRequest defines model for WSBroadcastRequest.
type WSBroadcastRequest struct {
	// Data Event data payload
	Data map[string]interface{} `json:"data"`

	// Event Event name to broadcast
	Event string `json:"event"`
}

// WSBroadcastResponse defines model for WSBroadcastResponse.
type WSBroadcastResponse struct {
	// Clients Number of clients reached
	Clients int `json:"clients"`

	// Message Response message
	Message string `json:"message"`

	// Success Whether broadcast was successful
	Success bool `json:"success"`
}

// WSMetricsResponse defines model for WSMetricsResponse.
type WSMetricsResponse struct {
	// ConnectedClients Number of connected clients
	ConnectedClients int `json:"connectedClients"`

	// EventsByType Count of events by type
	EventsByType map[string]int `json:"eventsByType"`

	// Timestamp Timestamp of the metrics
	Timestamp time.Time `json:"timestamp"`

	// TotalEvents Total events processed
	TotalEvents int `json:"totalEvents"`
}

// WSStatsResponse defines model for WSStatsResponse.
type WSStatsResponse struct {
	// ClientIds List of connected client IDs
	ClientIds []string `json:"clientIds"`

	// ConnectedClients Number of connected clients
	ConnectedClients int `json:"connectedClients"`

	// Timestamp Timestamp of the stats
	Timestamp time.Time `json:"timestamp"`
}

// WorkerInfo defines model for WorkerInfo.
type WorkerInfo struct {
	// Concurrency Number of concurrent jobs for this worker
	Concurrency int `json:"concurrency"`

	// Count Number of active worker jobs with this name/topic
	Count *int `json:"count,omitempty"`

	// DisplayName Human-readable worker name
	DisplayName string `json:"display_name"`

	// Name Job topic/worker name (e.g., exif_process, image_process)
	Name string `json:"name"`
}

// WorkerJob defines model for WorkerJob.
type WorkerJob struct {
	// Command Job command
	Command *string `json:"command"`

	// CompletedAt Completed timestamp
	CompletedAt *time.Time `json:"completed_at"`

	// EnqueuedAt Enqueued timestamp
	EnqueuedAt time.Time `json:"enqueued_at"`

	// ErrorCode Error code if failed
	ErrorCode *string `json:"error_code"`

	// ErrorMsg Error message if failed
	ErrorMsg *string `json:"error_msg"`

	// ImageUid Related image UID
	ImageUid *string `json:"image_uid"`

	// Payload Job payload
	Payload *string `json:"payload"`

	// StartedAt Started timestamp
	StartedAt *time.Time `json:"started_at"`

	// Status Job status
	Status string `json:"status"`

	// Topic Job topic
	Topic string `json:"topic"`

	// Type Job type
	Type string `json:"type"`

	// Uid Job UID
	Uid string `json:"uid"`
}

// WorkerJobCreateRequest defines model for WorkerJobCreateRequest.
type WorkerJobCreateRequest struct {
	// Command Command to execute (all=process all, missing=process missing)
	Command WorkerJobCreateRequestCommand `json:"command"`

	// Type Job topic (e.g., exif_process, image_process)
	Type string `json:"type"`

	// Uids Image UIDs to process (optional, if omitted all images are considered)
	Uids *[]string `json:"uids,omitempty"`
}

// WorkerJobCreateRequestCommand Command to execute (all=process all, missing=process missing)
type WorkerJobCreateRequestCommand string

// WorkerJobEnqueueResponse defines model for WorkerJobEnqueueResponse.
type WorkerJobEnqueueResponse struct {
	// Count Count of enqueued jobs
	Count *int `json:"count,omitempty"`

	// Message Response message
	Message string `json:"message"`
}

// WorkerJobStatsResponse defines model for WorkerJobStatsResponse.
type WorkerJobStatsResponse struct {
	// QueuedByTopic Queued jobs by topic
	QueuedByTopic map[string]int `json:"queued_by_topic"`

	// Running Total running jobs
	Running int `json:"running"`

	// RunningByTopic Running jobs by topic
	RunningByTopic map[string]int `json:"running_by_topic"`
}

// WorkerJobsResponse defines model for WorkerJobsResponse.
type WorkerJobsResponse struct {
	// Items List of jobs
	Items []WorkerJob `json:"items"`

	// Total Total count of jobs
	Total int `json:"total"`
}

// WorkerRegisterRequest defines model for WorkerRegisterRequest.
type WorkerRegisterRequest struct {
	// Concurrency Number of concurrent jobs for this worker
	Concurrency *int `json:"concurrency,omitempty"`

	// Name Job topic/worker name (e.g., exif_process, image_process)
	Name string `json:"name"`
}

// WorkersListResponse defines model for WorkersListResponse.
type WorkersListResponse struct {
	// Items List of workers
	Items []WorkerInfo `json:"items"`
}

// UpdateUserSettingJSONBody defines parameters for UpdateUserSetting.
type UpdateUserSettingJSONBody struct {
	// Value New setting value
	Value string `json:"value"`
}

// UpdateUserSettingParams defines parameters for UpdateUserSetting.
type UpdateUserSettingParams struct {
	// Name Setting name (e.g. 'theme', 'notifications_email')
	Name string `form:"name" json:"name"`
}

// AdminDeleteUserJSONBody defines parameters for AdminDeleteUser.
type AdminDeleteUserJSONBody struct {
	// Force If true, permanently deletes the user and all associated data (sessions, settings).
	Force *bool `json:"force,omitempty"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	// Email User email address
	Email openapi_types.Email `json:"email"`

	// Password User password
	Password string `json:"password"`
}

// InitiateOAuthParams defines parameters for InitiateOAuth.
type InitiateOAuthParams struct {
	// Provider OAuth provider (google or github)
	Provider InitiateOAuthParamsProvider `form:"provider" json:"provider"`
}

// InitiateOAuthParamsProvider defines parameters for InitiateOAuth.
type InitiateOAuthParamsProvider string

// CompleteOAuthParams defines parameters for CompleteOAuth.
type CompleteOAuthParams struct {
	// Code Authorization code from OAuth provider
	Code string `form:"code" json:"code"`

	// State State parameter for CSRF protection
	State string `form:"state" json:"state"`
}

// CompleteOAuthParamsProvider defines parameters for CompleteOAuth.
type CompleteOAuthParamsProvider string

// ListCollectionsParams defines parameters for ListCollections.
type ListCollectionsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Page Page index (0-based)
	Page *int `form:"page,omitempty" json:"page,omitempty"`
}

// DeleteCollectionImagesJSONBody defines parameters for DeleteCollectionImages.
type DeleteCollectionImagesJSONBody struct {
	// Uids List of image UIDs
	Uids []string `json:"uids"`
}

// ListCollectionImagesParams defines parameters for ListCollectionImages.
type ListCollectionImagesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// AddCollectionImagesJSONBody defines parameters for AddCollectionImages.
type AddCollectionImagesJSONBody struct {
	// Uids List of image UIDs
	Uids []string `json:"uids"`
}

// DownloadImagesParams defines parameters for DownloadImages.
type DownloadImagesParams struct {
	// Token Download token from /download/sign (required)
	Token string `form:"token" json:"token"`

	// Password Password if the token is password-protected (optional)
	Password *string `form:"password,omitempty" json:"password,omitempty"`
}

// GetEventHistoryParams defines parameters for GetEventHistory.
type GetEventHistoryParams struct {
	// Limit Maximum number of events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetEventsSinceParams defines parameters for GetEventsSince.
type GetEventsSinceParams struct {
	// Cursor Cursor ID to fetch events after
	Cursor *uint64 `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// DeleteImagesBulkJSONBody defines parameters for DeleteImagesBulk.
type DeleteImagesBulkJSONBody struct {
	// Force Force deletion
	Force *bool `json:"force,omitempty"`

	// Uids List of image UIDs
	Uids []string `json:"uids"`
}

// ListImagesParams defines parameters for ListImages.
type ListImagesParams struct {
	// Limit Number of images per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Page Current page index (0-based) of images being fetched
	Page   *int                    `form:"page,omitempty" json:"page,omitempty"`
	SortBy *ListImagesParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// Order Ascending or descending of the phots
	Order *string `form:"order,omitempty" json:"order,omitempty"`
}

// ListImagesParamsSortBy defines parameters for ListImages.
type ListImagesParamsSortBy string

// UploadImageByUrlTextBody defines parameters for UploadImageByUrl.
type UploadImageByUrlTextBody = string

// GetImageExifParams defines parameters for GetImageExif.
type GetImageExifParams struct {
	// Simple When true, return the stored simplified EXIF object from the DB (otherwise read raw EXIF from file)
	Simple *bool `form:"simple,omitempty" json:"simple,omitempty"`
}

// GetImageFileParams defines parameters for GetImageFile.
type GetImageFileParams struct {
	// Format Output format for transformation
	Format *GetImageFileParamsFormat `form:"format,omitempty" json:"format,omitempty"`

	// Width Width for transformation
	Width *int `form:"width,omitempty" json:"width,omitempty"`

	// Height Height for transformation
	Height *int `form:"height,omitempty" json:"height,omitempty"`

	// Quality Quality for transformation (0-100)
	Quality *int `form:"quality,omitempty" json:"quality,omitempty"`

	// Download Set to "1" to force download mode (requires token)
	Download *GetImageFileParamsDownload `form:"download,omitempty" json:"download,omitempty"`

	// Token Download token (required when download=1)
	Token *string `form:"token,omitempty" json:"token,omitempty"`

	// Password Password for password-protected tokens (optional)
	Password *string `form:"password,omitempty" json:"password,omitempty"`
}

// GetImageFileParamsFormat defines parameters for GetImageFile.
type GetImageFileParamsFormat string

// GetImageFileParamsDownload defines parameters for GetImageFile.
type GetImageFileParamsDownload string

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	// Status Filter by job status
	Status *ListJobsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Topic Filter by job topic
	Topic *string `form:"topic,omitempty" json:"topic,omitempty"`

	// Limit Number of jobs per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Page Page index (0-based)
	Page *int `form:"page,omitempty" json:"page,omitempty"`
}

// ListJobsParamsStatus defines parameters for ListJobs.
type ListJobsParamsStatus string

// ExecuteSearchParams defines parameters for ExecuteSearch.
type ExecuteSearchParams struct {
	// Q Search query string (e.g. "johannesburg rating:>=4")
	Q string `form:"q" json:"q"`

	// Limit Max items per category
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Page Page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`
}

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = UserCreate

// UpdateCurrentUserJSONRequestBody defines body for UpdateCurrentUser for application/json ContentType.
type UpdateCurrentUserJSONRequestBody = UserUpdate

// DoUserOnboardingJSONRequestBody defines body for DoUserOnboarding for application/json ContentType.
type DoUserOnboardingJSONRequestBody = UserOnboardingBody

// UpdatePasswordJSONRequestBody defines body for UpdatePassword for application/json ContentType.
type UpdatePasswordJSONRequestBody = UserPasswordUpdate

// UpdateUserSettingJSONRequestBody defines body for UpdateUserSetting for application/json ContentType.
type UpdateUserSettingJSONRequestBody UpdateUserSettingJSONBody

// UpdateUserSettingsBatchJSONRequestBody defines body for UpdateUserSettingsBatch for application/json ContentType.
type UpdateUserSettingsBatchJSONRequestBody = UserSettingUpdateRequest

// AdminCreateUserJSONRequestBody defines body for AdminCreateUser for application/json ContentType.
type AdminCreateUserJSONRequestBody = AdminUserCreate

// AdminDeleteUserJSONRequestBody defines body for AdminDeleteUser for application/json ContentType.
type AdminDeleteUserJSONRequestBody AdminDeleteUserJSONBody

// AdminUpdateUserJSONRequestBody defines body for AdminUpdateUser for application/json ContentType.
type AdminUpdateUserJSONRequestBody = AdminUserUpdate

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = APIKeyCreate

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// CreateCollectionJSONRequestBody defines body for CreateCollection for application/json ContentType.
type CreateCollectionJSONRequestBody = CollectionCreate

// UpdateCollectionJSONRequestBody defines body for UpdateCollection for application/json ContentType.
type UpdateCollectionJSONRequestBody = CollectionUpdate

// DeleteCollectionImagesJSONRequestBody defines body for DeleteCollectionImages for application/json ContentType.
type DeleteCollectionImagesJSONRequestBody DeleteCollectionImagesJSONBody

// AddCollectionImagesJSONRequestBody defines body for AddCollectionImages for application/json ContentType.
type AddCollectionImagesJSONRequestBody AddCollectionImagesJSONBody

// DownloadImagesJSONRequestBody defines body for DownloadImages for application/json ContentType.
type DownloadImagesJSONRequestBody = DownloadRequest

// SignDownloadJSONRequestBody defines body for SignDownload for application/json ContentType.
type SignDownloadJSONRequestBody = SignDownloadRequest

// BroadcastWSEventJSONRequestBody defines body for BroadcastWSEvent for application/json ContentType.
type BroadcastWSEventJSONRequestBody = WSBroadcastRequest

// SendToWSClientJSONRequestBody defines body for SendToWSClient for application/json ContentType.
type SendToWSClientJSONRequestBody = WSBroadcastRequest

// DeleteImagesBulkJSONRequestBody defines body for DeleteImagesBulk for application/json ContentType.
type DeleteImagesBulkJSONRequestBody DeleteImagesBulkJSONBody

// UploadImageMultipartRequestBody defines body for UploadImage for multipart/form-data ContentType.
type UploadImageMultipartRequestBody = ImageUploadRequest

// UploadImageByUrlTextRequestBody defines body for UploadImageByUrl for text/plain ContentType.
type UploadImageByUrlTextRequestBody = UploadImageByUrlTextBody

// UpdateImageJSONRequestBody defines body for UpdateImage for application/json ContentType.
type UpdateImageJSONRequestBody = ImageUpdate

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = WorkerJobCreateRequest

// RegisterWorkerJSONRequestBody defines body for RegisterWorker for application/json ContentType.
type RegisterWorkerJSONRequestBody = WorkerRegisterRequest

// UpdateSessionJSONRequestBody defines body for UpdateSession for application/json ContentType.
type UpdateSessionJSONRequestBody = SessionUpdate

// SetupSuperadminJSONRequestBody defines body for SetupSuperadmin for application/json ContentType.
type SetupSuperadminJSONRequestBody = SuperadminSetupRequest
