// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package dto

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for JobCreateRequestCommand.
const (
	All     JobCreateRequestCommand = "all"
	Missing JobCreateRequestCommand = "missing"
	Single  JobCreateRequestCommand = "single"
)

// Defines values for UserRole.
const (
	UserRoleAdmin      UserRole = "admin"
	UserRoleGuest      UserRole = "guest"
	UserRoleSuperadmin UserRole = "superadmin"
	UserRoleUser       UserRole = "user"
)

// Defines values for InitiateOAuthParamsProvider.
const (
	InitiateOAuthParamsProviderGithub InitiateOAuthParamsProvider = "github"
	InitiateOAuthParamsProviderGoogle InitiateOAuthParamsProvider = "google"
)

// Defines values for CompleteOAuthParamsProvider.
const (
	CompleteOAuthParamsProviderGithub CompleteOAuthParamsProvider = "github"
	CompleteOAuthParamsProviderGoogle CompleteOAuthParamsProvider = "google"
)

// Defines values for GetImageFileParamsFormat.
const (
	Avif GetImageFileParamsFormat = "avif"
	Heif GetImageFileParamsFormat = "heif"
	Jpeg GetImageFileParamsFormat = "jpeg"
	Jpg  GetImageFileParamsFormat = "jpg"
	Png  GetImageFileParamsFormat = "png"
	Webp GetImageFileParamsFormat = "webp"
)

// Defines values for GetImageFileParamsDownload.
const (
	N1 GetImageFileParamsDownload = "1"
)

// APIKey defines model for APIKey.
type APIKey struct {
	CreatedAt   time.Time  `json:"created_at"`
	Description *string    `json:"description"`
	ExpiresAt   *time.Time `json:"expires_at"`
	KeyHashed   string     `json:"key_hashed"`
	LastUsedAt  *time.Time `json:"last_used_at"`
	Name        *string    `json:"name,omitempty"`
	Revoked     bool       `json:"revoked"`
	RevokedAt   *time.Time `json:"revoked_at,omitempty"`
	Scopes      *[]string  `json:"scopes,omitempty"`
	Uid         string     `json:"uid"`
	UpdatedAt   time.Time  `json:"updated_at"`
	User        *User      `json:"user,omitempty"`
}

// APIKeyCreate defines model for APIKeyCreate.
type APIKeyCreate struct {
	Description *string    `json:"description"`
	ExpiresAt   *time.Time `json:"expires_at"`
	Name        *string    `json:"name,omitempty"`
	Scopes      *[]string  `json:"scopes,omitempty"`
}

// APIKeyCreateResponse defines model for APIKeyCreateResponse.
type APIKeyCreateResponse struct {
	ConsumerKey string     `json:"consumer_key"`
	ExpiresAt   *time.Time `json:"expires_at"`
}

// APIKeyListResponse defines model for APIKeyListResponse.
type APIKeyListResponse struct {
	Count int      `json:"count"`
	Items []APIKey `json:"items"`
}

// AddImagesResponse defines model for AddImagesResponse.
type AddImagesResponse struct {
	Added bool    `json:"added"`
	Error *string `json:"error,omitempty"`
}

// Collection defines model for Collection.
type Collection struct {
	CreatedAt   time.Time          `json:"created_at"`
	CreatedBy   *User              `json:"created_by,omitempty"`
	Description *string            `json:"description,omitempty"`
	ImageCount  int                `json:"image_count"`
	Images      *[]CollectionImage `json:"images,omitempty"`
	Name        string             `json:"name"`
	Private     *bool              `json:"private"`
	Thumbnail   *Image             `json:"thumbnail,omitempty"`
	Uid         string             `json:"uid"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// CollectionCreate defines model for CollectionCreate.
type CollectionCreate struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	Private     *bool   `json:"private"`
}

// CollectionDetailResponse defines model for CollectionDetailResponse.
type CollectionDetailResponse struct {
	CreatedAt   time.Time  `json:"created_at"`
	CreatedBy   *User      `json:"created_by,omitempty"`
	Description *string    `json:"description,omitempty"`
	ImageCount  *int       `json:"image_count,omitempty"`
	Images      ImagesPage `json:"images"`
	Name        string     `json:"name"`
	Private     *bool      `json:"private"`
	Thumbnail   *Image     `json:"thumbnail,omitempty"`
	Uid         string     `json:"uid"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

// CollectionImage defines model for CollectionImage.
type CollectionImage struct {
	AddedAt time.Time `json:"added_at"`
	AddedBy *User     `json:"added_by,omitempty"`
	Uid     string    `json:"uid"`
}

// CollectionListResponse defines model for CollectionListResponse.
type CollectionListResponse struct {
	Count *int         `json:"count,omitempty"`
	Href  *string      `json:"href,omitempty"`
	Items []Collection `json:"items"`
	Limit int          `json:"limit"`
	Next  *string      `json:"next,omitempty"`
	Page  int          `json:"page"`
	Prev  *string      `json:"prev,omitempty"`
}

// CollectionUpdate defines model for CollectionUpdate.
type CollectionUpdate struct {
	Description  *string `json:"description,omitempty"`
	Name         *string `json:"name,omitempty"`
	OwnerUID     *string `json:"ownerUID,omitempty"`
	Private      *bool   `json:"private,omitempty"`
	ThumbnailUID *string `json:"thumbnailUID,omitempty"`
}

// DeleteAssetsResponse defines model for DeleteAssetsResponse.
type DeleteAssetsResponse struct {
	Message *string `json:"message,omitempty"`
	Results []struct {
		Deleted bool    `json:"deleted"`
		Error   *string `json:"error,omitempty"`
		Uid     string  `json:"uid"`
	} `json:"results"`
}

// DeleteImagesResponse defines model for DeleteImagesResponse.
type DeleteImagesResponse struct {
	Deleted bool    `json:"deleted"`
	Error   *string `json:"error,omitempty"`
}

// DownloadRequest defines model for DownloadRequest.
type DownloadRequest struct {
	Filename *string  `json:"filename,omitempty"`
	Uids     []string `json:"uids"`
}

// DownloadToken Persistent download token with granular access controls
type DownloadToken struct {
	// AllowDownload Whether downloads are permitted with this token
	AllowDownload bool `json:"allow_download"`

	// AllowEmbed Whether embedding on external sites is allowed (false prevents hotlinking)
	AllowEmbed bool `json:"allow_embed"`

	// CreatedAt When this token was created
	CreatedAt time.Time `json:"created_at"`

	// Description Optional description of this download link
	Description *string `json:"description"`

	// ExpiresAt When this token expires (null for no expiry)
	ExpiresAt *time.Time `json:"expires_at"`

	// ImageUids Array of authorized image UIDs
	ImageUids []string `json:"image_uids"`

	// Password Optional bcrypt hash of password (null if no password protection)
	Password *string `json:"password"`

	// ShowMetadata Whether to include EXIF and metadata in responses
	ShowMetadata bool `json:"show_metadata"`

	// Uid 64-character hex token that serves as both unique identifier and authorization key
	Uid string `json:"uid"`

	// UpdatedAt When this token was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// EventHistoryResponse defines model for EventHistoryResponse.
type EventHistoryResponse struct {
	Count  int           `json:"count"`
	Events []EventRecord `json:"events"`
}

// EventRecord defines model for EventRecord.
type EventRecord struct {
	Data      map[string]interface{} `json:"data"`
	Event     string                 `json:"event"`
	Timestamp time.Time              `json:"timestamp"`
}

// Image defines model for Image.
type Image struct {
	CreatedAt     time.Time      `json:"created_at"`
	Description   *string        `json:"description,omitempty"`
	Exif          *ImageEXIF     `json:"exif,omitempty"`
	Height        int32          `json:"height"`
	ImageMetadata *ImageMetadata `json:"image_metadata,omitempty"`
	ImagePaths    ImagePaths     `json:"image_paths"`
	Name          string         `json:"name"`
	Private       bool           `json:"private"`
	Processed     bool           `json:"processed"`
	TakenAt       *time.Time     `json:"taken_at"`
	Uid           string         `json:"uid"`
	UpdatedAt     time.Time      `json:"updated_at"`
	UploadedBy    *User          `json:"uploaded_by,omitempty"`
	Width         int32          `json:"width"`
}

// ImageEXIF defines model for ImageEXIF.
type ImageEXIF struct {
	Aperture         *string `json:"aperture,omitempty"`
	DateTime         *string `json:"date_time,omitempty"`
	DateTimeOriginal *string `json:"date_time_original,omitempty"`
	ExifVersion      *string `json:"exif_version,omitempty"`
	ExposureTime     *string `json:"exposure_time,omitempty"`
	ExposureValue    *string `json:"exposure_value,omitempty"`
	FNumber          *string `json:"f_number,omitempty"`
	Flash            *string `json:"flash,omitempty"`
	FocalLength      *string `json:"focal_length,omitempty"`
	Iso              *string `json:"iso,omitempty"`
	Latitude         *string `json:"latitude,omitempty"`
	LensModel        *string `json:"lens_model,omitempty"`
	Longitude        *string `json:"longitude,omitempty"`
	Make             *string `json:"make,omitempty"`
	Model            *string `json:"model,omitempty"`
	ModifyDate       *string `json:"modify_date,omitempty"`
	Orientation      *string `json:"orientation,omitempty"`
	Rating           *string `json:"rating,omitempty"`
	Resolution       *string `json:"resolution,omitempty"`
	Software         *string `json:"software,omitempty"`
	WhiteBalance     *string `json:"white_balance,omitempty"`
}

// ImageMetadata defines model for ImageMetadata.
type ImageMetadata struct {
	Checksum         string    `json:"checksum"`
	ColorSpace       string    `json:"color_space"`
	FileCreatedAt    time.Time `json:"file_created_at"`
	FileModifiedAt   time.Time `json:"file_modified_at"`
	FileName         string    `json:"file_name"`
	FileSize         *int64    `json:"file_size,omitempty"`
	FileType         string    `json:"file_type"`
	Keywords         *[]string `json:"keywords,omitempty"`
	Label            *string   `json:"label,omitempty"`
	Metadata         *string   `json:"metadata,omitempty"`
	OriginalFileName *string   `json:"original_file_name,omitempty"`

	// Rating User-assigned rating (0-5). Null = unrated
	Rating    *int    `json:"rating"`
	Thumbhash *string `json:"thumbhash,omitempty"`
}

// ImagePaths defines model for ImagePaths.
type ImagePaths struct {
	Original  string  `json:"original"`
	Preview   string  `json:"preview"`
	Raw       *string `json:"raw,omitempty"`
	Thumbnail string  `json:"thumbnail"`
}

// ImageUpdate defines model for ImageUpdate.
type ImageUpdate struct {
	Description   *string    `json:"description"`
	Exif          *ImageEXIF `json:"exif,omitempty"`
	ImageMetadata *struct {
		Keywords *[]string `json:"keywords,omitempty"`
		Label    *string   `json:"label"`
		Rating   *int      `json:"rating"`
	} `json:"image_metadata,omitempty"`
	Name    *string `json:"name,omitempty"`
	Private *bool   `json:"private,omitempty"`
}

// ImageUploadResponse defines model for ImageUploadResponse.
type ImageUploadResponse struct {
	Uid string `json:"uid"`
}

// ImagesPage defines model for ImagesPage.
type ImagesPage struct {
	Count *int             `json:"count,omitempty"`
	Href  *string          `json:"href,omitempty"`
	Items []ImagesResponse `json:"items"`
	Limit int              `json:"limit"`
	Next  *string          `json:"next,omitempty"`
	Page  int              `json:"page"`
	Prev  *string          `json:"prev,omitempty"`
}

// ImagesResponse defines model for ImagesResponse.
type ImagesResponse struct {
	AddedAt time.Time `json:"added_at"`
	AddedBy *User     `json:"added_by,omitempty"`
	Image   Image     `json:"image"`
}

// JobCountResponse defines model for JobCountResponse.
type JobCountResponse struct {
	Running int `json:"running"`
}

// JobCreateRequest defines model for JobCreateRequest.
type JobCreateRequest struct {
	// Command Command to execute (all=process all, missing=process missing, single=process one image)
	Command *JobCreateRequestCommand `json:"command,omitempty"`

	// ImageUid Image UID (required when command=single)
	ImageUid *string `json:"image_uid,omitempty"`

	// Type Job type (e.g., thumbnailGeneration, imageProcessing)
	Type string `json:"type"`
}

// JobCreateRequestCommand Command to execute (all=process all, missing=process missing, single=process one image)
type JobCreateRequestCommand string

// JobEnqueueResponse defines model for JobEnqueueResponse.
type JobEnqueueResponse struct {
	Count   *int   `json:"count,omitempty"`
	Message string `json:"message"`
}

// JobInfo defines model for JobInfo.
type JobInfo struct {
	Id     string `json:"id"`
	Status string `json:"status"`
	Topic  string `json:"topic"`
}

// JobListResponse defines model for JobListResponse.
type JobListResponse struct {
	Items []JobInfo `json:"items"`
}

// JobStatsResponse defines model for JobStatsResponse.
type JobStatsResponse struct {
	QueuedByTopic  map[string]int `json:"queued_by_topic"`
	Running        int            `json:"running"`
	RunningByTopic map[string]int `json:"running_by_topic"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// OAuthUserData defines model for OAuthUserData.
type OAuthUserData struct {
	Email   openapi_types.Email `json:"email"`
	Name    string              `json:"name"`
	Picture string              `json:"picture"`
}

// Session defines model for Session.
type Session struct {
	ClientId   *string    `json:"client_id,omitempty"`
	ClientIp   *string    `json:"client_ip,omitempty"`
	ClientName *string    `json:"client_name,omitempty"`
	CreatedAt  time.Time  `json:"created_at"`
	ExpiresAt  *time.Time `json:"expires_at,omitempty"`
	LastActive *time.Time `json:"last_active,omitempty"`
	LoginAt    *time.Time `json:"login_at,omitempty"`
	LoginIp    *string    `json:"login_ip,omitempty"`
	RefId      *string    `json:"ref_id,omitempty"`
	Status     *int       `json:"status,omitempty"`
	Timeout    *int64     `json:"timeout,omitempty"`
	Token      string     `json:"token"`
	Uid        string     `json:"uid"`
	UpdatedAt  time.Time  `json:"updated_at"`
	User       *User      `json:"user,omitempty"`
	UserAgent  *string    `json:"user_agent,omitempty"`
	UserUid    string     `json:"user_uid"`
}

// SignDownloadRequest Request to create a download token
type SignDownloadRequest struct {
	// AllowDownload Allow downloads using this token (default true)
	AllowDownload *bool `json:"allow_download,omitempty"`

	// AllowEmbed Allow embedding images on external sites (default false to prevent hotlinking)
	AllowEmbed *bool `json:"allow_embed,omitempty"`

	// Description Optional description of this share/download link
	Description *string `json:"description,omitempty"`

	// ExpiresIn Time in seconds until the token expires (0 for no expiry, default 900 = 15 minutes)
	ExpiresIn *int `json:"expires_in,omitempty"`

	// Password Optional password protection for the token (will be bcrypt hashed)
	Password *string `json:"password,omitempty"`

	// ShowMetadata Include EXIF and other metadata in responses (default true)
	ShowMetadata *bool `json:"show_metadata,omitempty"`

	// Uids Array of image UIDs to include in the download token
	Uids *[]string `json:"uids,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Role      UserRole  `json:"role"`
	Uid       string    `json:"uid"`
	UpdatedAt time.Time `json:"updated_at"`
	Username  string    `json:"username"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserCreate defines model for UserCreate.
type UserCreate struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// WSBroadcastRequest defines model for WSBroadcastRequest.
type WSBroadcastRequest struct {
	Data  map[string]interface{} `json:"data"`
	Event string                 `json:"event"`
}

// WSBroadcastResponse defines model for WSBroadcastResponse.
type WSBroadcastResponse struct {
	Clients int    `json:"clients"`
	Message string `json:"message"`
	Success bool   `json:"success"`
}

// WSMetricsResponse defines model for WSMetricsResponse.
type WSMetricsResponse struct {
	ConnectedClients int            `json:"connectedClients"`
	EventsByType     map[string]int `json:"eventsByType"`
	Timestamp        time.Time      `json:"timestamp"`
	TotalEvents      int            `json:"totalEvents"`
}

// WSStatsResponse defines model for WSStatsResponse.
type WSStatsResponse struct {
	ClientIds        []string  `json:"clientIds"`
	ConnectedClients int       `json:"connectedClients"`
	Timestamp        time.Time `json:"timestamp"`
}

// WorkerJob defines model for WorkerJob.
type WorkerJob struct {
	Command     *string    `json:"command"`
	CompletedAt *time.Time `json:"completed_at"`
	EnqueuedAt  time.Time  `json:"enqueued_at"`
	ErrorCode   *string    `json:"error_code"`
	ErrorMsg    *string    `json:"error_msg"`
	ImageUid    *string    `json:"image_uid"`
	Payload     *string    `json:"payload"`
	StartedAt   *time.Time `json:"started_at"`
	Status      string     `json:"status"`
	Topic       string     `json:"topic"`
	Type        string     `json:"type"`
	Uid         string     `json:"uid"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// InitiateOAuthParams defines parameters for InitiateOAuth.
type InitiateOAuthParams struct {
	// Provider OAuth provider (google or github)
	Provider InitiateOAuthParamsProvider `form:"provider" json:"provider"`
}

// InitiateOAuthParamsProvider defines parameters for InitiateOAuth.
type InitiateOAuthParamsProvider string

// CompleteOAuthParams defines parameters for CompleteOAuth.
type CompleteOAuthParams struct {
	// Code Authorization code from OAuth provider
	Code string `form:"code" json:"code"`

	// State State parameter for CSRF protection
	State string `form:"state" json:"state"`
}

// CompleteOAuthParamsProvider defines parameters for CompleteOAuth.
type CompleteOAuthParamsProvider string

// ListCollectionsParams defines parameters for ListCollections.
type ListCollectionsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Page Page index (0-based)
	Page *int `form:"page,omitempty" json:"page,omitempty"`
}

// DeleteCollectionImagesJSONBody defines parameters for DeleteCollectionImages.
type DeleteCollectionImagesJSONBody struct {
	Uids []string `json:"uids"`
}

// ListCollectionImagesParams defines parameters for ListCollectionImages.
type ListCollectionImagesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// AddCollectionImagesJSONBody defines parameters for AddCollectionImages.
type AddCollectionImagesJSONBody struct {
	Uids []string `json:"uids"`
}

// DownloadImagesParams defines parameters for DownloadImages.
type DownloadImagesParams struct {
	// Token Download token from /download/sign (required)
	Token string `form:"token" json:"token"`

	// Password Password if the token is password-protected (optional)
	Password *string `form:"password,omitempty" json:"password,omitempty"`
}

// GetEventHistoryParams defines parameters for GetEventHistory.
type GetEventHistoryParams struct {
	// Limit Maximum number of events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetEventsSinceParams defines parameters for GetEventsSince.
type GetEventsSinceParams struct {
	// Cursor Cursor ID to fetch events after
	Cursor *uint64 `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of events to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// DeleteImagesBulkJSONBody defines parameters for DeleteImagesBulk.
type DeleteImagesBulkJSONBody struct {
	Force *bool    `json:"force,omitempty"`
	Uids  []string `json:"uids"`
}

// ListImagesParams defines parameters for ListImages.
type ListImagesParams struct {
	// Limit Number of images per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Page Page index (0-based)
	Page *int `form:"page,omitempty" json:"page,omitempty"`
}

// UploadImageMultipartBody defines parameters for UploadImage.
type UploadImageMultipartBody struct {
	Data     openapi_types.File `json:"data"`
	Filename string             `json:"filename"`
}

// UploadImageByUrlTextBody defines parameters for UploadImageByUrl.
type UploadImageByUrlTextBody = string

// GetImageExifParams defines parameters for GetImageExif.
type GetImageExifParams struct {
	// Simple When true, return the stored simplified EXIF object from the DB (otherwise read raw EXIF from file)
	Simple *bool `form:"simple,omitempty" json:"simple,omitempty"`
}

// GetImageFileParams defines parameters for GetImageFile.
type GetImageFileParams struct {
	// Format Output format for transformation
	Format *GetImageFileParamsFormat `form:"format,omitempty" json:"format,omitempty"`

	// W Width for transformation
	W *int `form:"w,omitempty" json:"w,omitempty"`

	// H Height for transformation
	H *int `form:"h,omitempty" json:"h,omitempty"`

	// Quality Quality for transformation (0-100)
	Quality *int `form:"quality,omitempty" json:"quality,omitempty"`

	// Download Set to "1" to force download mode (requires token)
	Download *GetImageFileParamsDownload `form:"download,omitempty" json:"download,omitempty"`

	// Token Download token (required when download=1)
	Token *string `form:"token,omitempty" json:"token,omitempty"`

	// Password Password for password-protected tokens (optional)
	Password *string `form:"password,omitempty" json:"password,omitempty"`
}

// GetImageFileParamsFormat defines parameters for GetImageFile.
type GetImageFileParamsFormat string

// GetImageFileParamsDownload defines parameters for GetImageFile.
type GetImageFileParamsDownload string

// UpdateJobTypeConcurrencyJSONBody defines parameters for UpdateJobTypeConcurrency.
type UpdateJobTypeConcurrencyJSONBody struct {
	Concurrency int `json:"concurrency"`
}

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = UserCreate

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = APIKeyCreate

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// CreateCollectionJSONRequestBody defines body for CreateCollection for application/json ContentType.
type CreateCollectionJSONRequestBody = CollectionCreate

// UpdateCollectionJSONRequestBody defines body for UpdateCollection for application/json ContentType.
type UpdateCollectionJSONRequestBody = CollectionUpdate

// DeleteCollectionImagesJSONRequestBody defines body for DeleteCollectionImages for application/json ContentType.
type DeleteCollectionImagesJSONRequestBody DeleteCollectionImagesJSONBody

// AddCollectionImagesJSONRequestBody defines body for AddCollectionImages for application/json ContentType.
type AddCollectionImagesJSONRequestBody AddCollectionImagesJSONBody

// DownloadImagesJSONRequestBody defines body for DownloadImages for application/json ContentType.
type DownloadImagesJSONRequestBody = DownloadRequest

// SignDownloadJSONRequestBody defines body for SignDownload for application/json ContentType.
type SignDownloadJSONRequestBody = SignDownloadRequest

// BroadcastWSEventJSONRequestBody defines body for BroadcastWSEvent for application/json ContentType.
type BroadcastWSEventJSONRequestBody = WSBroadcastRequest

// SendToWSClientJSONRequestBody defines body for SendToWSClient for application/json ContentType.
type SendToWSClientJSONRequestBody = WSBroadcastRequest

// DeleteImagesBulkJSONRequestBody defines body for DeleteImagesBulk for application/json ContentType.
type DeleteImagesBulkJSONRequestBody DeleteImagesBulkJSONBody

// UploadImageMultipartRequestBody defines body for UploadImage for multipart/form-data ContentType.
type UploadImageMultipartRequestBody UploadImageMultipartBody

// UploadImageByUrlTextRequestBody defines body for UploadImageByUrl for text/plain ContentType.
type UploadImageByUrlTextRequestBody = UploadImageByUrlTextBody

// UpdateImageJSONRequestBody defines body for UpdateImage for application/json ContentType.
type UpdateImageJSONRequestBody = ImageUpdate

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = JobCreateRequest

// UpdateJobTypeConcurrencyJSONRequestBody defines body for UpdateJobTypeConcurrency for application/json ContentType.
type UpdateJobTypeConcurrencyJSONRequestBody UpdateJobTypeConcurrencyJSONBody
