// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package dto

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UserRole.
const (
	UserRoleAdmin      UserRole = "admin"
	UserRoleGuest      UserRole = "guest"
	UserRoleSuperadmin UserRole = "superadmin"
	UserRoleUser       UserRole = "user"
)

// Defines values for InitiateOAuthParamsProvider.
const (
	InitiateOAuthParamsProviderGithub InitiateOAuthParamsProvider = "github"
	InitiateOAuthParamsProviderGoogle InitiateOAuthParamsProvider = "google"
)

// Defines values for CompleteOAuthParamsProvider.
const (
	CompleteOAuthParamsProviderGithub CompleteOAuthParamsProvider = "github"
	CompleteOAuthParamsProviderGoogle CompleteOAuthParamsProvider = "google"
)

// Defines values for GetImageFileParamsFormat.
const (
	Avif GetImageFileParamsFormat = "avif"
	Heif GetImageFileParamsFormat = "heif"
	Jpeg GetImageFileParamsFormat = "jpeg"
	Jpg  GetImageFileParamsFormat = "jpg"
	Png  GetImageFileParamsFormat = "png"
	Webp GetImageFileParamsFormat = "webp"
)

// APIKeyResponse defines model for APIKeyResponse.
type APIKeyResponse struct {
	ConsumerKey string `json:"consumer_key"`
}

// AddImagesResponse defines model for AddImagesResponse.
type AddImagesResponse struct {
	Added bool    `json:"added"`
	Error *string `json:"error,omitempty"`
}

// Collection defines model for Collection.
type Collection struct {
	CreatedAt   time.Time          `json:"created_at"`
	CreatedBy   *User              `json:"created_by,omitempty"`
	Description *string            `json:"description,omitempty"`
	ImageCount  int                `json:"image_count"`
	Images      *[]CollectionImage `json:"images,omitempty"`
	Name        string             `json:"name"`
	Private     *bool              `json:"private"`
	Thumbnail   *Image             `json:"thumbnail,omitempty"`
	Uid         string             `json:"uid"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// CollectionCreate defines model for CollectionCreate.
type CollectionCreate struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	Private     *bool   `json:"private"`
}

// CollectionDetailResponse defines model for CollectionDetailResponse.
type CollectionDetailResponse struct {
	CreatedAt   time.Time  `json:"created_at"`
	CreatedBy   *User      `json:"created_by,omitempty"`
	Description *string    `json:"description,omitempty"`
	ImageCount  *int       `json:"image_count,omitempty"`
	Images      ImagesPage `json:"images"`
	Name        string     `json:"name"`
	Private     *bool      `json:"private"`
	Thumbnail   *Image     `json:"thumbnail,omitempty"`
	Uid         string     `json:"uid"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

// CollectionImage defines model for CollectionImage.
type CollectionImage struct {
	AddedAt time.Time `json:"added_at"`
	AddedBy *User     `json:"added_by,omitempty"`
	Uid     string    `json:"uid"`
}

// CollectionListResponse defines model for CollectionListResponse.
type CollectionListResponse struct {
	Count  *int         `json:"count,omitempty"`
	Href   *string      `json:"href,omitempty"`
	Items  []Collection `json:"items"`
	Limit  int          `json:"limit"`
	Next   *string      `json:"next,omitempty"`
	Offset int          `json:"offset"`
	Prev   *string      `json:"prev,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Image defines model for Image.
type Image struct {
	CreatedAt     time.Time      `json:"created_at"`
	Description   *string        `json:"description,omitempty"`
	Exif          *ImageEXIF     `json:"exif,omitempty"`
	Height        int32          `json:"height"`
	ImageMetadata *ImageMetadata `json:"image_metadata,omitempty"`
	ImagePaths    ImagePaths     `json:"image_paths"`
	Name          string         `json:"name"`
	Private       bool           `json:"private"`
	Processed     bool           `json:"processed"`
	Uid           string         `json:"uid"`
	UpdatedAt     time.Time      `json:"updated_at"`
	UploadedBy    *User          `json:"uploaded_by,omitempty"`
	Width         int32          `json:"width"`
}

// ImageEXIF defines model for ImageEXIF.
type ImageEXIF struct {
	Aperture         *string `json:"aperture,omitempty"`
	DateTime         *string `json:"date_time,omitempty"`
	DateTimeOriginal *string `json:"date_time_original,omitempty"`
	ExifVersion      *string `json:"exif_version,omitempty"`
	ExposureTime     *string `json:"exposure_time,omitempty"`
	Flash            *string `json:"flash,omitempty"`
	FocalLength      *string `json:"focal_length,omitempty"`
	Iso              *string `json:"iso,omitempty"`
	Latitude         *string `json:"latitude,omitempty"`
	LensModel        *string `json:"lens_model,omitempty"`
	Longitude        *string `json:"longitude,omitempty"`
	Make             *string `json:"make,omitempty"`
	Model            *string `json:"model,omitempty"`
	ModifyDate       *string `json:"modify_date,omitempty"`
	Orientation      *string `json:"orientation,omitempty"`
	Rating           *string `json:"rating,omitempty"`
	Resolution       *string `json:"resolution,omitempty"`
	Software         *string `json:"software,omitempty"`
	WhiteBalance     *string `json:"white_balance,omitempty"`
}

// ImageMetadata defines model for ImageMetadata.
type ImageMetadata struct {
	Checksum         string    `json:"checksum"`
	ColorSpace       string    `json:"color_space"`
	FileCreatedAt    time.Time `json:"file_created_at"`
	FileModifiedAt   time.Time `json:"file_modified_at"`
	FileName         string    `json:"file_name"`
	FileSize         *int64    `json:"file_size,omitempty"`
	FileType         string    `json:"file_type"`
	Keywords         *[]string `json:"keywords,omitempty"`
	Label            *string   `json:"label,omitempty"`
	OriginalFileName *string   `json:"original_file_name,omitempty"`
	Thumbhash        *string   `json:"thumbhash,omitempty"`
}

// ImagePaths defines model for ImagePaths.
type ImagePaths struct {
	Original  string  `json:"original"`
	Preview   string  `json:"preview"`
	Raw       *string `json:"raw,omitempty"`
	Thumbnail string  `json:"thumbnail"`
}

// ImageUploadResponse defines model for ImageUploadResponse.
type ImageUploadResponse struct {
	Id string `json:"id"`
}

// ImagesPage defines model for ImagesPage.
type ImagesPage struct {
	Count  *int             `json:"count,omitempty"`
	Href   *string          `json:"href,omitempty"`
	Items  []ImagesResponse `json:"items"`
	Limit  int              `json:"limit"`
	Next   *string          `json:"next,omitempty"`
	Offset int              `json:"offset"`
	Prev   *string          `json:"prev,omitempty"`
}

// ImagesResponse defines model for ImagesResponse.
type ImagesResponse struct {
	AddedAt time.Time `json:"added_at"`
	AddedBy *User     `json:"added_by,omitempty"`
	Image   Image     `json:"image"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// OAuthUserData defines model for OAuthUserData.
type OAuthUserData struct {
	Email   openapi_types.Email `json:"email"`
	Name    string              `json:"name"`
	Picture string              `json:"picture"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Role      UserRole  `json:"role"`
	Uid       string    `json:"uid"`
	UpdatedAt time.Time `json:"updated_at"`
	Username  string    `json:"username"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserCreate defines model for UserCreate.
type UserCreate struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// InitiateOAuthParams defines parameters for InitiateOAuth.
type InitiateOAuthParams struct {
	// Provider OAuth provider (google or github)
	Provider InitiateOAuthParamsProvider `form:"provider" json:"provider"`
}

// InitiateOAuthParamsProvider defines parameters for InitiateOAuth.
type InitiateOAuthParamsProvider string

// CompleteOAuthParams defines parameters for CompleteOAuth.
type CompleteOAuthParams struct {
	// Code Authorization code from OAuth provider
	Code string `form:"code" json:"code"`

	// State State parameter for CSRF protection
	State string `form:"state" json:"state"`
}

// CompleteOAuthParamsProvider defines parameters for CompleteOAuth.
type CompleteOAuthParamsProvider string

// ListCollectionsParams defines parameters for ListCollections.
type ListCollectionsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListCollectionImagesParams defines parameters for ListCollectionImages.
type ListCollectionImagesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// AddCollectionImagesJSONBody defines parameters for AddCollectionImages.
type AddCollectionImagesJSONBody struct {
	Uids []string `json:"uids"`
}

// UploadImageMultipartBody defines parameters for UploadImage.
type UploadImageMultipartBody struct {
	Data     openapi_types.File `json:"data"`
	Filename string             `json:"filename"`
}

// UploadImageByUrlTextBody defines parameters for UploadImageByUrl.
type UploadImageByUrlTextBody = string

// GetImageFileParams defines parameters for GetImageFile.
type GetImageFileParams struct {
	Format  *GetImageFileParamsFormat `form:"format,omitempty" json:"format,omitempty"`
	W       *int                      `form:"w,omitempty" json:"w,omitempty"`
	H       *int                      `form:"h,omitempty" json:"h,omitempty"`
	Quality *int                      `form:"quality,omitempty" json:"quality,omitempty"`
}

// GetImageFileParamsFormat defines parameters for GetImageFile.
type GetImageFileParamsFormat string

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = UserCreate

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// CreateCollectionJSONRequestBody defines body for CreateCollection for application/json ContentType.
type CreateCollectionJSONRequestBody = CollectionCreate

// AddCollectionImagesJSONRequestBody defines body for AddCollectionImages for application/json ContentType.
type AddCollectionImagesJSONRequestBody AddCollectionImagesJSONBody

// UploadImageMultipartRequestBody defines body for UploadImage for multipart/form-data ContentType.
type UploadImageMultipartRequestBody UploadImageMultipartBody

// UploadImageByUrlTextRequestBody defines body for UploadImageByUrl for text/plain ContentType.
type UploadImageByUrlTextRequestBody = UploadImageByUrlTextBody
